### ISSUE TITLE
Builtin Terminal not opened

### ISSUE THREAD

**Issue by shiv123shiv123** [coder/code-server#2935]
When i try to open terminal then it automatically close and give this error notice in notification 

`The terminal process failed to launch: A native exception occurred during launch (Cannot find module '../build/Release/pty.node' Require stack: - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/node-pty/lib/index.js - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js).`

**Comment by jsjoeio** [comment]
@shiv123shiv123 can you please fill out the bug report template? It's difficult to know what could be the issue without having that information (though it looks like you're missing a module potentially). That will help us help you faster! Thank you!

**Comment by shiv123shiv123** [comment]
Os - kali-distro installed on termux with proot
Desktop - xfce4
Arch. - armhf
Code-server - 3.9.1
Installed with yarn and npm
All thing work good but builtin terminal not open, the module pty.node already exist.

**Comment by jsjoeio** [comment]
If you're using Termux, I'm assuming you followed the docs [here](https://github.com/cdr/code-server/blob/main/docs/install.md#termux).

>  the module pty.node already exist.
Hmm.. what version of Node are you using?

**Comment by shiv123shiv123** [comment]
I did not install code server in termux directly instead in kali distro which install in termux with proot and using script you given in readme.md
`Node version -- v12.21.0`
`Yarn version -- 1.22.10`

**Comment by jsjoeio** [comment]
Ah okay. Hmm...can you run code-server with the `--log debug` flag? i.e. `code-server --log debug` and post the logs here?

**Comment by shiv123shiv123** [comment]
I think you need this? 
` [2021-03-19T20:13:29.670Z] info  code-server 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015
[2021-03-19T20:13:29.677Z] info  Using user-data-dir ~/.local/share/code-server
[2021-03-19T20:13:29.781Z] info  Using config file ~/.config/code-server/config.yaml
[2021-03-19T20:13:29.781Z] info  HTTP server listening on http://127.0.0.1:8080 
[2021-03-19T20:13:29.782Z] info    - Authentication is enabled
[2021-03-19T20:13:29.782Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-03-19T20:13:29.783Z] info    - Not serving HTTPS 
[2021-03-19T20:15:08.252Z] debug redirecting from / to ./login
[2021-03-19T20:15:14.660Z] debug no valid cookie doman {"host":"localhost"}
[2021-03-19T20:15:14.666Z] debug redirecting from /login to ./
[2021-03-19T20:15:14.753Z] debug forking vs code...
[2021-03-19T20:15:20.384Z] debug setting up vs code...
[2021-03-19T20:15:20.398Z] debug vscode got message from code-server {"type":"init"}
[2021-03-19T20:15:20.622Z] warn  vscode Unable to retrieve mac address (unexpected format)
[2021-03-19T20:15:24.850Z] debug vscode got message from code-server {"type":"socket"}
[2021-03-19T20:15:24.903Z] debug vscode New connection {"token":"18c5a1ca-af8b-4231-808d-4ca5be167afe"}
[2021-03-19T20:15:27.742Z] debug vscode got message from code-server {"type":"socket"}
[2021-03-19T20:15:28.354Z] debug vscode New connection {"token":"9bbba093-4ddd-451e-ab69-3242093279ca"}
[2021-03-19T20:15:28.541Z] debug got latest version {"latest":"3.9.1"}
[2021-03-19T20:15:28.545Z] debug comparing versions {"current":"3.9.1","latest":"3.9.1"}
[2021-03-19T20:15:38.498Z] debug Creating terminal {"id":0,"terminals":0}
[2021-03-19T20:15:38.530Z] debug Resolved shell launch configuration {"id":0}
[2021-03-19T20:15:38.541Z] debug Resolved terminal environment {"id":0}
[2021-03-19T20:15:38.545Z] debug Created terminal {"id":0}
[2021-03-19T20:15:38.987Z] debug Terminal bound {"id":0}
[2021-03-19T20:15:38.989Z] debug Terminal replaying {"id":0}
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/node-pty/lib/index.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
`

**Comment by oxy** [comment]
This looks like a build issue - I think Kali is based on debian, so with some luck you should be able to just grab our arm64 `.deb` and install it. Can you try that and report back?

**Comment by shiv123shiv123** [comment]
I tried that before but this version i.e arm64 gives error 500 when open it in browser. Seems it doesn't support armhf kali.

**Comment by Jackzmc** [comment]
> 
> 
> Os - kali-distro installed on termux with proot
> Desktop - xfce4
> Arch. - armhf
> Code-server - 3.9.1
> Installed with yarn and npm
> All thing work good but builtin terminal not open, the module pty.node already exist.

I'm having the exact same issue,
All features of code server seem to work fine (Have not tested in depth) but opening the terminal returns the same errors,
and returns the same error (cannot find module '../build/Debug/pty.node') in the debug log

Running on Oracle Linux Server release 7.9 (aarch64). Running on the latest version code-server-3.10.2-arm64

**Comment by Merith-TK** [comment]
Termux
![image](https://user-images.githubusercontent.com/10422110/125146521-0a49cb00-e0db-11eb-97ab-df0370d3e8b3.png)

`uname` reports armv8, but software is 100% armv7

**Comment by jsjoeio** [comment]
Hmm 🤔 cc @oxy or @code-asher

**Comment by Merith-TK** [comment]
IMPLIED EDIT TO MY PREVIOUS THING
Some device manufacturers like to use an arm64 CPU+Kernel, but only load 32bit linkers and programs, such as the kindle fire, 

if you run `uname` and it says an armv8 architecture, and then run `file $(which sh)` in termux and it returns it is compiled for an arm7 architecture, this is why, manufacture's dont bother shipping 64bit compatibility in their software

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/125335717-b8cf5500-e301-11eb-98fe-6f2e2f84bfb6.png)

**Comment by code-asher** [comment]
Interesting, I wonder if setting `npm_config_arch` to the right
architecture will make `yarn` and `npm` work?

**Comment by Merith-TK** [comment]
> Interesting, I wonder if setting `npm_config_arch` to the right architecture will make `yarn` and `npm` work?

On termux, if you install nodejs thought the package manager `pkg install nodejs` it will download and install the correct version, as termux gets around this annoying issue by checking the actual preinstalled *linker* during setup to install the correct files,

**Comment by everyplace** [comment]
+1 for this issue as well. Running on a Raspberry Pi Zero 2, freshly installed Raspberry Pi OS, updated etc.
![IMG_0187](https://user-images.githubusercontent.com/95356/144688466-19e42495-def6-472c-bf3c-924301072602.png)

**Comment by yonggithub** [comment]
+1 for this issue as well. I use alpine build docker file.
Dockerfile:
```
FROM node:14.19.0-alpine as builder
RUN set -x \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    && apk upgrade \
    && apk --no-cache add alpine-sdk bash libstdc++ libc6-compat \
    && npm config set python python3 \
RUN git clone --recursive https://github.com/cdr/code-server.git
RUN cd code-server
RUN yarn global add code-server

ENV PASSWORD=changeme
ENTRYPOINT code-server --bind-addr 0:8443
```
![image](https://user-images.githubusercontent.com/25076827/153748997-a69ab42e-2a20-4576-9d42-2db384356365.png)

thanks.

**Comment by code-asher** [comment]
Looks like the pty module did not get installed.  Were there any errors
during the code-server install?  Running `npm rebuild` in the
`vendor/modules/code-oss-dev` directory might help.

**Comment by tomatopickle** [comment]
This is still happening, I'm on Windows 10. Any updates on this?

**Comment by jsjoeio** [comment]
@tomatopickle can you share logs or screenshots?

**Comment by tomatopickle** [comment]
Sure, here's the log from Code Server

![image](https://user-images.githubusercontent.com/65482369/167830119-f93b77d2-b57c-4a96-93a0-3584f1e927d0.png)
And here's the log from the terminal
`
yarn run v1.22.15
warning package.json: No license field
$ C:\Users\mohammed\node_modules\.bin\code-server
[2022-05-11T10:35:58.859Z] info  code-server 4.4.0 b088ec7adf9e17bc75215f79e21498eb40da03ed
[2022-05-11T10:35:58.861Z] info  Using user-data-dir ~\AppData\Local\code-server\Data
[2022-05-11T10:35:58.892Z] info  Using config file ~\AppData\Roaming\code-server\Config\config.yaml
[2022-05-11T10:35:58.892Z] info  HTTP server listening on http://127.0.0.1:8080/
[2022-05-11T10:35:58.892Z] info    - Authentication is disabled
[2022-05-11T10:35:58.892Z] info    - Not serving HTTPS
Error: Could not locate the bindings file. Tried:
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\build\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\build\Debug\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\build\Release\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\out\Debug\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\Debug\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\out\Release\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\Release\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\build\default\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\compiled\16.15.0\win32\x64\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\addon-build\release\install-root\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\addon-build\debug\install-root\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\addon-build\default\install-root\spdlog.node
 → C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\lib\binding\node-v93-win32-x64\spdlog.node
    at bindings (C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\mohammed\node_modules\code-server\lib\vscode\node_modules\spdlog\index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.require._load (C:\Users\mohammed\node_modules\code-server\out\node\plugin.js:50:74)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:101)
    at e.load (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:4:1720)
    at e.load (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:3:10695)
    at d (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:10300)
    at Object.errorback (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:10421)
    at e.triggerErrorback (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:3:11059)
    at C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:3:10765
    at e.load (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:4:1737)
    at e.load (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:3:10695)
    at d (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:10300)
    at i._loadModule (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:10430)
    at i._resolve (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:6:452)
    at i.defineModule (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:6142)
    at i._relativeRequire (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:6828)
    at r (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\loader.js:5:9406)
    at E (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:80:53207)
    at new Promise (<anonymous>)
    at w (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:80:53187)
    at _createSpdLogLogger (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:80:54022)
    at new _ (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:80:53829)
    at ye (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:138:135825)
    at G (C:\Users\mohammed\node_modules\code-server\lib\vscode\out\vs\server\node\server.main.js:146:7643) {
  tries: [
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\build\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\build\\Debug\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\build\\Release\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\out\\Debug\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\Debug\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\out\\Release\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\Release\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\build\\default\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\compiled\\16.15.0\\win32\\x64\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\addon-build\\release\\install-root\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\addon-build\\debug\\install-root\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\addon-build\\default\\install-root\\spdlog.node',
    'C:\\Users\\mohammed\\node_modules\\code-server\\lib\\vscode\\node_modules\\spdlog\\lib\\binding\\node-v93-win32-x64\\spdlog.node'
  ],
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[13:36:02] Extension host agent started.
`

**Comment by jsjoeio** [comment]
Hmm...did you try the `npm rebuild` trick? I _think_ you'd run it in `C:\Users\mohammed\node_modules\code-server\lib\vscode`

**Comment by AMasetti** [comment]
I tried the `npm rebuild` trick on a Pi4 v1.2 and I'm still getting the same error, I even installed pty manually.

**Comment by jsjoeio** [comment]
Did that fix it?

**Comment by jjerry-k** [comment]
So I tried `yarn` on /usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev

But, I got errors about dependency x11, xkbfile.

So I installed that.

`sudo apt install libx11-dev libxkbfile-dev`

**Comment by reDpz** [comment]
got this issue as well
`The terminal process failed to launch: A native exception occurred during launch (Cannot find module '../build/Release/pty.node'
Require stack:
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/index.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-fork.js).`

**Comment by 2270057439** [comment]
termux ，got this issue as well


``` 
The terminal process failed to launch: A native exception occurred during launch (Cannot find module 
'../build/Release/pty.node' Require stack: - 
/data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js - 
/data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/index.js - 
/data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-amd.js -
 /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-fork.js).
```

**Comment by niloy940** [comment]
The terminal process failed to launch: A native exception occurred during launch (Cannot find module '../build/Release/pty.node'
Require stack:
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/index.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-fork.js).

**Comment by code-asher** [comment]
The error suggests that module failed to install during the build process.  I am not sure where the Termux build happens but looking at the build logs would probably be a good place to start.  Might need to add some verbose flags to `npm`.

**Comment by Tzxhy** [comment]
I found the problem in node-pty. Shows:

```txt
[IPC Library: Pty Host] import error:  Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/code-server/lib/vscode/node_modules/node-pty/build/Release/pty.node)
```

**Comment by Fmstrat** [comment]
I am also experiencing this problem in the latest version with alpine. This wasn't happening on the previous version.

**Comment by code-asher** [comment]
Are you installing glibc alongside musl or something?

`version GLIBC_2.28 not found` I believe means the version of glibc is too old.

**Comment by code-asher** [comment]
Closing for inactivity.  Also note the minimum has increased to glibc 2.28 with code-server 4.17.0.
