### ISSUE TITLE
Color syntax didn't work in Jupyter notebook

### ISSUE THREAD

**Issue by quentin9696** [coder/code-server#3268]
## OS/Web Information

- Web Browser: Firefox 88.0
- Local OS: Windows
- Remote OS: Ubuntu 20.04
- Remote Architecture: Jupyter + proxy server plugin
- `code-server --version`: 3.9.3

## Steps to Reproduce

1. Install code server on a notebook (eg jupyter/datascience-notebook)
``` bash
jupyter serverextension enable --sys-prefix jupyter_server_proxy
curl -sSLo /resources/code-server.deb \
  https://github.com/cdr/code-server/releases/download/v3.9.3/code-server_3.9.3_amd64.deb

apt-get update

apt install /resources/code-server.deb --yes

echo <<-EOF 
c.ServerProxy.servers = {
    'codeserver': {
        'command': ['code-server', '--auth', 'none', '--disable-telemetry', '--disable-update-check', '--bind-addr', '127.0.0.1:3080'],
        'port': 3080,
        'timeout': 120,
        'launcher_entry': {
            'enabled': True,
            'title': 'Code-Server',
        },
    },
}
EOF>> /etc/jupyter/jupyter_notebook_config.py
```
2. Run the docker using jupyter (not in standalone, but with Jupyter)

## Expected
We should have the syntax coloration. 

## Actual

Don't have the syntax coloration.

## Logs

In dev console, we got this error message 

```
logger.ts:173 error [Service Worker] registration: Failed to register a ServiceWorker: The provided scope ('/codeserver/') or scriptURL ('/usr/lib/code-server/dist/serviceWorker.js') includes a disallowed escape character. 
TypeError: Failed to register a ServiceWorker: The provided scope ('/codeserver/') or scriptURL ('/usr/lib/code-server/dist/serviceWorker.js') includes a disallowed escape character.    
at /usr/lib/code-server/dist/register.js:14:1767    
at /usr/lib/code-server/dist/register.js:14:1301    
at Object.next (/usr/lib/code-server/dist/register.js:14:1406)    
at /usr/lib/code-server/dist/register.js:14:319    
at new Promise (<anonymous>)    
at e (usr/lib/code-server/dist/register.js:14:67)    
at n (/usr/lib/code-server/dist/register.js:14:1530)    
at Object.parcelRequire.O6cr.../common/util (/usr/lib/code-server/dist/register.js:14:2147)    
at f (/usr/lib/code-server/dist/register.js:1:468)    
at parcelRequire.i8TM (/usr/lib/code-server/dist/register.js:1:771)
```

## Notes

Only when running code-server via jupyter. If I run the docker in standalone mode, it's ok

**Comment by jsjoeio** [comment]
Thanks for opening this issue and posting the logs. We'll investigate this.
