### ISSUE TITLE
UI stays on 'file participants' for almost a minute

### ISSUE THREAD

**Issue by AceSpadeAble** [coder/code-server#3842]
## OS/Web Information

- Web Browser: Firefox
- Local OS: Ubuntu 20.04.2 LTS
- Remote OS: Debian 10
- Remote Architecture: 64 bit
- `code-server --version`: 3.11.0

## 
Hello 👋

I am creating my own docker image with code-server 3.11.0 right now.
After opening code-server in docker container, I have noticed that actions (create, copy, delete) 
in explorer panel take a really long time 
to complete but in bash those commands are working just fine. —>

## Screenshot

![Screenshot 2021-07-23 at 16 12 49](https://user-images.githubusercontent.com/33558885/126795512-4df2f1b6-4960-47f1-a567-688c4dcee21a.png)

One more thing. When I click cancel the task is completed right away. 
It’s almost like the command is completed but code-server 
must still check something. This is code-server without any extensions, so no ESlint for example.

 ## Steps to Reproduce

1. Create docker image from release-standalone folder
2. Use “docker run -d ‘docker image’ —auth none”
3. Try to create file/folder using explorer panel buttons

## Logs

Using code-server --log debug
shows that nothing is wrong but when I use 'docker logs' on that container 
It is showing this error. 

`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /usr/local/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/local/lib/vscode/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/local/lib/vscode/out/vs/loader.js:5:101)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1722)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)
    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/local/lib/vscode/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/local/lib/vscode/out/vs/loader.js:3:10613)
    at /usr/local/lib/vscode/out/vs/loader.js:3:10319
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1739)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)
    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/local/lib/vscode/out/vs/loader.js:5:10444)
    at r._resolve (/usr/local/lib/vscode/out/vs/loader.js:6:452)
    at r.defineModule (/usr/local/lib/vscode/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/local/lib/vscode/out/vs/loader.js:5:6831)
    at n (/usr/local/lib/vscode/out/vs/loader.js:5:9420)
    at P.f (/usr/local/lib/vscode/out/vs/server/entry.js:24:4512)
    at new Promise (<anonymous>)
    at P (/usr/local/lib/vscode/out/vs/server/entry.js:24:4492)
    at _createSpdLogLogger (/usr/local/lib/vscode/out/vs/server/entry.js:24:5472)
    at new _ (/usr/local/lib/vscode/out/vs/server/entry.js:24:5288)
    at Ae.initializeServices (/usr/local/lib/vscode/out/vs/server/entry.js:41:95222)
    at async Ae.initialize (/usr/local/lib/vscode/out/vs/server/entry.js:41:92228)
    at async process.<anonymous> (/usr/local/lib/vscode/out/vs/server/entry.js:41:98916) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /usr/local/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/local/lib/vscode/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/local/lib/vscode/out/vs/loader.js:5:101)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1722)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)
    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/local/lib/vscode/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/local/lib/vscode/out/vs/loader.js:3:10613)
    at /usr/local/lib/vscode/out/vs/loader.js:3:10319
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1739)
    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)
    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/local/lib/vscode/out/vs/loader.js:5:10444)
    at r._resolve (/usr/local/lib/vscode/out/vs/loader.js:6:452)
    at r.defineModule (/usr/local/lib/vscode/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/local/lib/vscode/out/vs/loader.js:5:6831)
    at n (/usr/local/lib/vscode/out/vs/loader.js:5:9420)
    at P.f (/usr/local/lib/vscode/out/vs/server/entry.js:24:4512)
    at new Promise (<anonymous>)
    at P (/usr/local/lib/vscode/out/vs/server/entry.js:24:4492)
    at _createSpdLogLogger (/usr/local/lib/vscode/out/vs/server/entry.js:24:5472)
    at new _ (/usr/local/lib/vscode/out/vs/server/entry.js:24:5288)
    at Ae.initializeServices (/usr/local/lib/vscode/out/vs/server/entry.js:41:95222)
    at async Ae.initialize (/usr/local/lib/vscode/out/vs/server/entry.js:41:92228)
    at async process.<anonymous> (/usr/local/lib/vscode/out/vs/server/entry.js:41:98916) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

[2021-07-23T14:12:16.626Z] error exthost console {"arguments":"[\"Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /usr/local/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)\\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)\\n    at Module.load (internal/modules/cjs/loader.js:928:32)\\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\\n    at Function.n._load (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27915)\\n    at Module.require (internal/modules/cjs/loader.js:952:19)\\n    at require (internal/modules/cjs/helpers.js:88:18)\\n    at bindings (/usr/local/lib/vscode/node_modules/bindings/bindings.js:112:48)\\n    at Object.<anonymous> (/usr/local/lib/vscode/node_modules/spdlog/index.js:3:35)\\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\\n    at Module.load (internal/modules/cjs/loader.js:928:32)\\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\\n    at Function.n._load (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27915)\\n    at Module.require (internal/modules/cjs/loader.js:952:19)\\n    at require (internal/modules/cjs/helpers.js:88:18)\\n    at t (/usr/local/lib/vscode/out/vs/loader.js:5:101)\\n    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1722)\\n    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)\\n    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)\\n    at Object.errorback (/usr/local/lib/vscode/out/vs/loader.js:5:10435)\\n    at r.triggerErrorback (/usr/local/lib/vscode/out/vs/loader.js:3:10613)\\n    at /usr/local/lib/vscode/out/vs/loader.js:3:10319\\n    at r.load (/usr/local/lib/vscode/out/vs/loader.js:4:1739)\\n    at r.load (/usr/local/lib/vscode/out/vs/loader.js:3:10249)\\n    at l (/usr/local/lib/vscode/out/vs/loader.js:5:10314)\\n    at r._loadModule (/usr/local/lib/vscode/out/vs/loader.js:5:10444)\\n    at r._resolve (/usr/local/lib/vscode/out/vs/loader.js:6:452)\\n    at r.defineModule (/usr/local/lib/vscode/out/vs/loader.js:5:6145)\\n    at r._relativeRequire (/usr/local/lib/vscode/out/vs/loader.js:5:6831)\\n    at n (/usr/local/lib/vscode/out/vs/loader.js:5:9420)\\n    at l (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:75:7572)\\n    at new Promise (<anonymous>)\\n    at k (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:75:7552)\\n    at C._createSpdLogLogger (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:75:8532)\\n    at new C (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:75:8348)\\n    at new C (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:86356)\\n    at s._createInstance (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:1371)\\n    at s._createServiceInstance (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:3772)\\n    at s._createServiceInstanceWithOwner (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:3288)\\n    at s._createAndCacheServiceInstance (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:2963)\\n    at s._safeCreateAndCacheServiceInstance (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:2161)\\n    at s._getOrCreateServiceInstance (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:1882)\\n    at Object.get (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:450)\\n    at /usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:9543\\n    at s.invokeFunction (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:73:319)\\n    at new E (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:9523)\\n    at Object.i [as startExtensionHostProcess] (/usr/local/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31795)\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\"]","token":"5e547c73-fe79-465f-a09c-30229483d0e7"}`

I found also this in issues https://github.com/cdr/code-server/discussions/2308#:~:text=failed%20to%20start-,%232308,-Unanswered but I don’t know if this is what creates that problem.

**Comment by jsjoeio** [comment]
I am spitballing here, but looking at the error:
```logs
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /usr/local/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)
```

Temporarily, would [upgrading the glib version](https://pkgs.org/download/libstdc++.so.6(GLIBCXX_3.4.26)(64bit)) inside your environment fix this? 

Not sure why this is happening though. cc the experts @oxy @code-asher

**Comment by code-asher** [comment]
Agreed with the assessment, it appears that whatever you used to build
`release-standalone` is using a newer version of glib than the Docker
image that is running the build.

One way to resolve this would be to use the same Docker image for both
building and running the build.

**Comment by AceSpadeAble** [comment]
Thanks for answers. Tried all day building images with different versions of Libstdc++.so.6
For example : `apt-get update && apt-get install libstdc++6`
When i get to this part of image building, the message i get is 
`libstdc++6 is already the newest version (8.3.0-6).` but the error with 'GLIBCXX_3.4.26' not found
is still present. Now I will try to do what you have suggested.

**Comment by AdamZaczek** [comment]
@AceSpadeAble is on vacation so let me say this - your suggestion worked! Thanks @code-asher
