### ISSUE TITLE
VS code's inbuilt simple browser fails to load

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3845]
## OS/Web Information

- Web Browser: Brave
- Local OS: macOS
- Remote OS: macOS
- Remote Architecture: N/A
- `code-server --version`: 3.11

## Steps to Reproduce

1. Open Command Palette (Ctrl/Cmd + shift + p / F1)
2. Type Simple Browser
3. Select Simple Browser(show)
4. Type any url
5. (optional) check browser console for errors

## Expected

A new tab in the Workspace should load with the site loaded.

## Actual

Nothing loads.

## Logs

I don't believe these logs are related but posting regardless. 

```logs
[Service Worker] registration: Failed to register a ServiceWorker for scope ('http://localhost:8080/') with script ('http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/dist/serviceWorker.js'): A bad HTTP response code (404) was received when fetching the script. TypeError: Failed to register a ServiceWorker for scope ('http://localhost:8080/') with script ('http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/dist/serviceWorker.js'): A bad HTTP response code (404) was received when fetching the script.
  
  ERR Unable to write to Folder Settings because no resource is provided.: Error: Unable to write to Folder Settings because no resource is provided.
    at b.reject (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:15316)
    at b.resolveAndValidate (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:19500)
    at b.doWriteConfiguration (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12506)
    at Object.factory (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12282)
    at y.consume (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15342)
    at http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15157
    at new Promise (<anonymous>)
    at y.queue (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15081)
    at b.writeConfiguration (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12267)
    at y.writeConfigurationValue (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:41475)
log.ts:296   

ERR Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
    at Object.a [as mnemonicMenuLabel] (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:75:37234)
    at F.<anonymous> (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:1921:3884)
    at n.fire (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:60:1855)
    at A.runner (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:662:6717)
    at A.doRun (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:17097)
    at A.onTimeout (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:17063)
```

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/126841918-816c40f2-f982-464c-a0e3-c11930302cd4.png)

## Notes

This issue can be reproduced in VS Code: Sort of?

It isn't working in my local version of VS Code (blank screen)

![image](https://user-images.githubusercontent.com/3806031/126841999-60e5078e-d429-4e37-873d-8d27df3922c4.png)

I'm getting this weird "Focus Lock" error at the bottom.

_Originally reported by @Blakeinstein in https://github.com/cdr/code-server/discussions/3844_

**Comment by Blakeinstein** [comment]
The focus lock is not an error or a bug. Its a feature. It shows when the webview is in focus, as in the keyboard and all inputs are currently being fed to the webview. I got completely different logs however. I will share them soon.

**Comment by jsjoeio** [comment]
> The focus lock is not an error or a bug. Its a feature. It shows when the webview is in focus, as in the keyboard and all inputs are currently being fed to the webview.

Whoops! lol thank you for clarifying.

> I guess since the webview had an index.html + an iframe. the html loads, but any css and js requested by said html isnt loaded at all? (Stuck in CORS, or just plain not found?)

Interesting...when you said webview it made me think of this [upstream issue](https://github.com/microsoft/vscode/issues/127770) we've been seeing reports about in the latest release. I wonder if they could be related.

**Comment by Blakeinstein** [comment]
> Interesting...when you said webview it made me think of this [upstream issue](https://github.com/microsoft/vscode/issues/127770) we've been seeing reports about in the latest release. I wonder if they could be related.

Could be. But since it failed on heroku as well, I dont think its an HTTPS problem? Well I am not totally sure, but I assume its a webview since electron has a webview api and since simple browser doesnt have a requirement on having a browser present in the system. I assumed it would be using webview. I havent seen simple browser being documented properly, Just found it being used in gitpod (try any frontend code template).

**Comment by jsjoeio** [comment]
Hmm...good point about Heroku. 

> If possible, can we have any webview components be served as iframes instead?

Great question. I'm not sure 🤔 @code-asher might know though

**Comment by Blakeinstein** [comment]
I totally missed the notes section, but some pages may not load in the vscode webview. Try something simple like https://xkcd.com instead

**Comment by code-asher** [comment]
I think the webview already uses an iframe? But it's been a while since
I've poked around the webview code.

**Comment by jonasdev** [comment]
Any solutions CRA projects?

**Comment by jsjoeio** [comment]
@jonasdev does this help? https://coder.com/docs/code-server/latest/guide#proxying-to-create-a-react-app

**Comment by willmil11** [comment]
What vscode theme are you using ? Looks so cool :)
