### ISSUE TITLE
Browser Extention Not Compliant

### ISSUE THREAD

**Issue by crazyn2** [coder/code-server#4096]
## OS/Web Information
1.
- Web Browser: Chromium
- Local OS: Windows 10/Ubuntu20.04
- Remote OS: Ubuntu20.04 Docker
- Remote Architecture: x86_64
- `code-server --version`: 3.11.1

## Steps to Reproduce
1.
```
$ docker run -d --name code-server -p 8080:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)" -e "TZ=Asia/Shanghai" --restart=always  -e "DOCKER_USER=$USER" codercom/code-server:lates
$ docker exec -it code-server bash
$ apt update && apt install vim chromium wget curl -y
$ curl -fsSL https://code-server.dev/install.sh | sh (upgrade 3.11.0 to 3.11.1)
$ exit (exit from docker container bash to local os bash)
```
2. install vscode extension Browser Preview (0.6.7 auchenberg)
![截取图片_20210903100107](https://user-images.githubusercontent.com/45783572/131939926-7574872d-527f-483c-8ec4-ba047da07db6.png)
3. refresh the browser and click the icon of Browser Preview 

## Expected
![expected_20210903101218](https://user-images.githubusercontent.com/45783572/131940165-0223f56e-ada2-4ed3-9168-ba95d6d01999.png)

## Actual

![actual_20210903101331](https://user-images.githubusercontent.com/45783572/131940267-cf7c23cf-607c-4d87-814f-44298599c9ec.png)

## Logs

    1. The most recent files from docker logs code-server.
 
```
[2021-09-03T01:33:21.861Z] info  code-server 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd
[2021-09-03T01:33:21.862Z] info  Using user-data-dir ~/.local/share/code-server
[2021-09-03T01:33:21.873Z] info  Using config file ~/.config/code-server/config.yaml
[2021-09-03T01:33:21.873Z] info  HTTP server listening on http://0.0.0.0:8080 
[2021-09-03T01:33:21.873Z] info    - Authentication is enabled
[2021-09-03T01:33:21.873Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-09-03T01:33:21.873Z] info    - Not serving HTTPS 
 INFO Installing extension: auchenberg.vscode-browser-preview
 WARN No ptyHost heartbeat after 6 seconds
 INFO Downloaded extension: auchenberg.vscode-browser-preview /home/coder/.local/share/code-server/CachedExtensionVSIXs/auchenberg.vscode-browser-preview-0.6.7
 INFO Extracted extension to /home/coder/.local/share/code-server/extensions/.3fca47c8-4b9d-474f-b381-d9eefdd7bba9: auchenberg.vscode-browser-preview
 INFO Renamed to /home/coder/.local/share/code-server/extensions/auchenberg.vscode-browser-preview-0.6.7
 INFO Installation completed. auchenberg.vscode-browser-preview
 INFO Extensions installed successfully: auchenberg.vscode-browser-preview
[2021-09-03T01:41:55.720Z] info  code-server 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e
[2021-09-03T01:41:55.721Z] info  Using user-data-dir ~/.local/share/code-server
[2021-09-03T01:41:55.733Z] info  Using config file ~/.config/code-server/config.yaml
[2021-09-03T01:41:55.733Z] info  HTTP server listening on http://0.0.0.0:8080 
[2021-09-03T01:41:55.733Z] info    - Authentication is enabled
[2021-09-03T01:41:55.733Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-09-03T01:41:55.733Z] info    - Not serving HTTPS 
[2021-09-03T01:41:56.668Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:41:56.686Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:11.690Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:11.708Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:26.800Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:26.816Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:46.821Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:42:46.837Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-03T01:45:36.019Z] warn  vscode Version mismatch (4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd instead of c680aae973d83583e4a73dc0c422f44021f0140e)
[2021-09-03T01:45:36.085Z] warn  vscode Version mismatch (4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd instead of c680aae973d83583e4a73dc0c422f44021f0140e)
[2021-09-03T01:45:36.141Z] warn  vscode Version mismatch (4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd instead of c680aae973d83583e4a73dc0c422f44021f0140e)
 WARN Resolved variables received without matching request 16
 WARN Resolved variables received without matching request 17
 WARN Resolved variables received without matching request 18
 WARN Resolved variables received without matching request 19
 WARN Resolved variables received without matching request 20
 WARN Resolved variables received without matching request 21
 WARN Resolved variables received without matching request 22
 WARN Resolved variables received without matching request 23
 WARN Resolved variables received without matching request 24
 WARN Resolved variables received without matching request 25
 WARN Resolved variables received without matching request 26
 WARN Resolved variables received without matching request 27
 WARN Resolved variables received without matching request 28
 WARN Resolved variables received without matching request 29
 WARN Resolved variables received without matching request 30

```
  
    2. The browser console.
```
    main.js:211 Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.
    at VM392 main.js:115
    at new Promise (<anonymous>)
    at VM392 main.js:115
(anonymous) @ main.js:211
(anonymous) @ main.js:209
main.js:291 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
    at createWebviewManager (VM392 main.js:115)
    at VM391 host.js:2
```
    3. The browser network tab.
    
[browser
_network.zip](https://github.com/cdr/code-server/files/7102877/browser.zip)

## Notes
By the way, I've tried several scenarios to address the coditions which make  bug reproduced.
1. Work
From now, I'm sure that when open browser Chromium or Firefox with URL http://127.0.0.1:8080 in remote OS sometimes.
```
$ docker run -d --name code-server -p 8080:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)" -e "TZ=Asia/Shanghai" --restart=always  -e "DOCKER_USER=$USER" codercom/code-server:lates
```

2. Not Work
```
$ docker run -d --name code-server -p 8090:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)" -e "TZ=Asia/Shanghai" --restart=always  -e "DOCKER_USER=$USER" codercom/code-server:lates
```
open browser with http://127.0.0.1:8090 in remote OS
3.Not Work
```
$ docker run -d --name code-server -p 8080:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)" -e "TZ=Asia/Shanghai" --restart=always  -e "DOCKER_USER=$USER" codercom/code-server:lates
```
4. Work
```
$ docker run -d --name code-server -p 8080:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)" -e "TZ=Asia/Shanghai" --restart=always  -e "DOCKER_USER=$USER" codercom/code-server:lates
```
ssh -L 8080:127.0.0.1:8080 -N -f user@server

open browser with http://127.0.0.1:8080 in local OS
open browser with http://[my domain]:1080.The 1080 was mapped to 8080 by router

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
>     main.js:211 Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.

I assume this is the cause of the issue. I imagine this extension loads in a webview which is why you're getting a blank scren.

Can you enable service workers?

**Comment by crazyn2** [comment]
Sir, how to enable service workers?

**Comment by jsjoeio** [comment]
Good question! 

Thinking out loud here, I see you're accessing code-server over HTTP (using 127.0.0.1 instead of localhost). I think this means the browser won't enable service workers (I could be wrong). So I think you'll need to serve it over HTTPS in order for this to work.

cc @code-asher is that right?

**Comment by code-asher** [comment]
Yeah service workers will be automatically enabled when using a secure context.

Local resources like 127.0.0.1 are considered a secure contexts: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure

For remote resources HTTPS is required.
