### ISSUE TITLE
When Markdown editor is scrolled, view of the preview is not updated

### ISSUE THREAD

**Issue by SitramSoft** [coder/code-server#4278]
## OS/Web Information

- Web Browser: Chrome Version 94.0.4606.61 (Official Build) (64-bit)
- Local OS: Windows 10
- Remote OS: Ubuntu 21.04, 5.11.0-36-generic
- Remote Architecture: x86_64
- `code-server --version`: 3.12.0 b37ff28a0a582aee84a8f961755d0cb40a4081db

## Steps to Reproduce

1. Open a Markdown file
2. Press "Open Preview to the Side" button in the upper right corner
3. Scroll trough the .md file

## Expected
Preview of the md file will scroll in sync with the source code

## Actual
Preview of the md file doesn't scroll in sync with the source code

## Logs

code-server-stderr.log
```
~/.local/share/code-server/coder-logs$ cat code-server-stderr.log
PROTOCOL CORRUPTION, LAST SAW MSG 0 AND HAVE NOW RECEIVED MSG 694
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
PROTOCOL CORRUPTION, LAST SAW MSG 0 AND HAVE NOW RECEIVED MSG 10030
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455:14)
    at p.write (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:204:769)
    at v.write (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:206:464)
    at p._writeNow (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:195:974)
    at Immediate.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:195:912)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EPIPE'
}

```

## Screenshot
N/A

## Notes
Both  options **Markdown › Preview: Scroll Editor With Preview** and **Markdown › Preview: Scroll Preview With Editor** are checked in Settings in User, Remote and Workspace.

I run code-server in a VM with authentication and HTTPS disabled. 
I access it from exterior trough NGINX proxy over https using certificates from let's encrypt.

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment]
Thanks for the notes! Looks like this is a bug, I was able to reproduce it locally.


https://user-images.githubusercontent.com/3806031/135529020-dc3fdc72-ac3e-424f-affc-3853bd0d677c.mov

## Logs

```javascript
dom.ts:46 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
c @ dom.ts:46
a @ dom.ts:67
registerTabsContainerListeners @ tabsTitleControl.ts:329
create @ tabsTitleControl.ts:158
T @ titleControl.ts:122
qt @ tabsTitleControl.ts:127
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
createTitleAreaControl @ editorGroupView.ts:475
Di @ editorGroupView.ts:205
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
createNew @ editorGroupView.ts:63
doCreateGroupView @ editorPart.ts:531
doAddGroup @ editorPart.ts:496
addGroup @ editorPart.ts:486
w @ editorGroupFinder.ts:75
E @ editorGroupFinder.ts:26
invokeFunction @ instantiationService.ts:61
openEditor @ editorService.ts:570
main.js:823 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ main.js:823
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/pre.js"}' (Error: Unable to resolve non-existing file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/pre.js"}')
    at ci.doReadFileStream (fileService.ts:541)
    at async w (resourceLoading.ts:68)
    at async _.loadResource (webviewElement.ts:643)
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-math/notebook-out/katex.min.css"}' (Error: Unable to resolve non-existing file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-math/notebook-out/katex.min.css"}')
    at ci.doReadFileStream (fileService.ts:541)
    at async w (resourceLoading.ts:68)
    at async _.loadResource (webviewElement.ts:643)
resourceLoading.ts:82 Error: Unable to read file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/index.js"}' (Error: Unable to resolve non-existing file 'vscode-remote://localhost:8080/vscode-resource?{"requestResourcePath":"/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/index.js"}')
    at ci.doReadFileStream (fileService.ts:541)
    at async w (resourceLoading.ts:68)
    at async _.loadResource (webviewElement.ts:643)
main.js:823 GET https://vscode-remote+localhost-003a8080.vscode-resource.vscode-webview.net/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/pre.js net::ERR_ABORTED 404
(anonymous) @ main.js:823
setTimeout (async)
m @ main.js:821
(anonymous) @ main.js:852
main.js:823 GET https://vscode-remote+localhost-003a8080.vscode-resource.vscode-webview.net/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-math/notebook-out/katex.min.css net::ERR_ABORTED 404
(anonymous) @ main.js:823
setTimeout (async)
m @ main.js:821
(anonymous) @ main.js:852
main.js:823 GET https://vscode-remote+localhost-003a8080.vscode-resource.vscode-webview.net/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/markdown-language-features/media/index.js net::ERR_ABORTED 404
```

![image](https://user-images.githubusercontent.com/3806031/135529178-c9f279d3-3887-44e2-b5b1-564945531104.png)

**Comment by SitramSoft** [comment]
Any fix in sight for this bug?

**Comment by jsjoeio** [comment]
No plans yet, but I can move it to an upcoming milestone so we consider fixing it faster!

**Comment by SitramSoft** [comment]
> No plans yet, but I can move it to an upcoming milestone so we consider fixing it faster!

This is great! Thank you!
