### ISSUE TITLE
Support VSCode version 1.61.0 or higher

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [coder/code-server#4653]
Currently, I am using code-server running on a Samsung Tablet within Termux, I have noticed one of my installed extensions was not working which was [Roblox LSP](https://github.com/NightrainsRbx/RobloxLsp), I have tried many different troubleshooting from recompiling native things and asking around at the Roblox Open Source Community Discord for hours until I discovered that the issue was the VSCode version being lower than 1.61.0:
```
[2021-12-19 17:41:55.821] [exthost] [error] Activating extension Nightrains.robloxlsp failed due to an error:
[2021-12-19 17:41:55.821] [exthost] [error] Error: The language client requires VS Code version ^1.61.0 but received version 1.60.0

at LanguageClient.checkVersion (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/node_modules/vscode-languageclient/lib/node/main.js:124:19)
at new LanguageClient (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/node_modules/vscode-languageclient/lib/node/main.js:105:18)
at start (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/out/languageserver.js:108:18)
at didOpenTextDocument (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/out/languageserver.js:326:26)
at Array.forEach (<anonymous>)
at Object.activate (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/out/languageserver.js:344:38)
at activate (/home/radiatedexodus/.local/share/code-server/extensions/nightrains.robloxlsp-1.5.4/client/out/extension.js:182:20)
at Function._callActivateOptional (/home/radiatedexodus/.local/lib/code-server-3.12.0/code-server-3.12.0-linux-arm64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14900)
at Function._callActivate (/home/radiatedexodus/.local/lib/code-server-3.12.0/code-server-3.12.0-linux-arm64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14576)
at /home/radiatedexodus/.local/lib/code-server-3.12.0/code-server-3.12.0-linux-arm64/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12779
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Promise.all (index 2)
```

I would appreciate it if you can atleast support VSCode version 1.61.0

**Comment by RealEthanPlayzDev** [comment]
An hacky workaround, I had to go to the extension folder, then go to ``client/node_modules/vscode-languageclient/lib/node/main.js`` and at line 124, comment out the ``throw new error`` statement so that the extension doesn't fail to load, this made the extension work fine however this workaround can break the extension in any new updates, I would still like to see VSCode version 1.61.0 being supported atleast

![Screenshot_20211220-010940_Chrome](https://user-images.githubusercontent.com/30568955/146686068-94b99d7f-5434-4d0d-95f3-6568d64812cd.jpg)

**Comment by fritterhoff** [comment]
FYI: The 4.0.0-prerelease is already based on 1.63.0 😉

**Comment by jsjoeio** [comment]
@fritterhoff is right! This shouldn't be an issue with the next release. You can use the 4.0.0-prerelease today. Closing this
