### ISSUE TITLE
[Bug]: MODULE_NOT_FOUND on Termux !

### ISSUE THREAD

**Issue by aariow** [coder/code-server#4849]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Local OS: Android/Termux
- `node --version`: `v17.*.*` & `v10.19.2`
- `code-server --version`: `v4.0.2`

### Steps to Reproduce

1. `curl -fsSL https://code-server.dev/install.sh | sh`
2. `code-server --bind-addr IP:PORT`

### Expected

Hey,
I've installed code-server v3.10 and it worked well on termux (virtual Ubuntu).
Now I'm trying to install version 4.0.2 but it gives me the same error with different approaches.
Tried to install code-server on Termux directly and even on Ubuntu (virtual). All the times I see MODULE_NOT_FOUND.
On the other hand, installing it by `yard global add code-server` wants Node.js v14 and that's impossible to downgrade Node.js on termux via `n` command.

### Actual

What should I do to make it work ?
Thanks in advance

### Logs

```bash
Ubuntu 20.04 LTS
Installing v4.0.2 of the arm64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.0.2_arm64.deb.incomplete -C - https://github.com/coder/code-server/releases/download/v4.0.2/code-server_4.0.2_arm64.deb
######################################################################## 100.0%
+ mv ~/.cache/code-server/code-server_4.0.2_arm64.deb.incomplete ~/.cache/code-server/code-server_4.0.2_arm64.deb
+ dpkg -i ~/.cache/code-server/code-server_4.0.2_arm64.deb
Selecting previously unselected package code-server.
(Reading database ... 12334 files and directories currently installed.)
Preparing to unpack .../code-server_4.0.2_arm64.deb ...
Unpacking code-server (4.0.2) ...
Setting up code-server (4.0.2) ...

deb package has been installed.

To have systemd start code-server now and restart on boot:
  sudo systemctl enable --now code-server@$USER
Or, if you don't want/need a background service you can run:
  code-server
root@localhost:~# sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
root@localhost:~# code-server --bind-addr 192.168.234.166:7070
/usr/lib/code-server/node_modules/@node-rs/argon2/index.js:201
    throw loadError
    ^

Error: Cannot find module '@node-rs/argon2-linux-arm64-gnu'
Require stack:
- /usr/lib/code-server/node_modules/@node-rs/argon2/index.js
- /usr/lib/code-server/out/node/util.js
- /usr/lib/code-server/out/node/cli.js
- /usr/lib/code-server/out/node/entry.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/code-server/node_modules/@node-rs/argon2/index.js:172:31)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/code-server/node_modules/@node-rs/argon2/index.js',
    '/usr/lib/code-server/out/node/util.js',
    '/usr/lib/code-server/out/node/cli.js',
    '/usr/lib/code-server/out/node/entry.js'
  ]
}

```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
The best thing to do is either stick with 3.12.0 on Termux or upgrade once 4.0.3 comes out.

In 4.0.2, we added a new argon2 package thinking it would help but it didn't work unfortunately.

We have some docs here for Termux: https://coder.com/docs/code-server/latest/termux
