### ISSUE TITLE
[Bug]: Blank screen and console outputs Unexpected token '.' (index): 79

### ISSUE THREAD

**Issue by BlankShrimp** [coder/code-server#4867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome v78
- Local OS: Windows10 1809
- Remote OS: Ubuntu20.04
- Remote Architecture: amd64
- `code-server --version`: 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
IMPORTANT: either local or remote environment is totally offline, no Internet connection at all. 

### Steps to Reproduce

1. Download and install code-server, using dpkg to install
2. Start code-server
3. Open browser and enter password
4. Authentication works fine, head to vscode page, but a blank screen showed

### Expected

Visit vscode as normal

### Actual

dark blank screen,
console outputs were as below: 
```
Uncaught SyntaxError: Unexpected token '.'   (index):79
Uncaught SyntaxError: Unexpected token '?'   notebookWebviewPreloads.js:3
Uncaught SyntaxError: Unexpected token '.'   workbench.js:3
```

### Logs

![image](https://user-images.githubusercontent.com/35521976/154034939-b5e2b112-510c-4b39-8703-76d9c015a9a7.png)
![image](https://user-images.githubusercontent.com/35521976/154035033-54e88eee-5b4b-4e1e-9e29-0b9cc554a3a3.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I'm not using HTTPS, but I'm guessing it's not related

**Comment by jsjoeio** [comment]
> I'm not using HTTPS, but I'm guessing it's not related

I see "notebookWebview" in your logs. Webviews need Service Workers and Service Workers only work with HTTPS 😢 That could be related but I'll try reproducing by running code-server offline.

**Comment by BlankShrimp** [comment]
> > I'm not using HTTPS, but I'm guessing it's not related
> 
> I see "notebookWebview" in your logs. Webviews need Service Workers and Service Workers only work with HTTPS 😢 That could be related but I'll try reproducing by running code-server offline.

Thank you very much. By saying "guessing it's not related", I had actually run the code-server online but without HTTPS successfully (online installed by install.sh, rather than offline installed via .deb). I'll also try installing .deb online to exclude more variables.

**Comment by jsjoeio** [comment]
Hmm...I ran code-server offline and it loaded 🤔 Though I did see a couple errors on the server.

## Video

https://user-images.githubusercontent.com/3806031/154119623-bde1fcdf-d334-446d-8505-676ec85f0c41.mov

## Logs

```logs
[2022-02-15T17:47:48.357Z] error child:24032 Uncaught exception: Unable to retrieve mac address (unexpected format)

Error: Unable to retrieve mac address (unexpected format)
    at P (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:46514)
    at f (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:48018)
    at async /usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:47876
[2022-02-15T17:47:48.358Z] error child:24032 Error: Unable to retrieve mac address (unexpected format)

Error: Unable to retrieve mac address (unexpected format)
    at P (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:46514)
    at f (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:48018)
    at async /usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:47876
    at Timeout._onTimeout (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:6:11466)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
Error: Unable to retrieve mac address (unexpected format)

Error: Unable to retrieve mac address (unexpected format)
    at P (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:46514)
    at f (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:48018)
    at async /usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:77:47876
    at Timeout._onTimeout (/usr/local/Cellar/code-server/4.0.2/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:6:11466)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by BlankShrimp** [comment]
Hmmm... intersting. I just tried standalone installation and the same error prompted. Any idea on missing some necessary libraries to my environment? 

-----------------------------------

Haha when I was typing the above msg I just noticed that the Chrome that I was using in my offline env was too old. I upgraded it and all works fine. How silly I am.
