### ISSUE TITLE
[Bug]: Install Plug error

### ISSUE THREAD

**Issue by XRSec** [coder/code-server#4941]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: mac
- Remote OS: centos
- Remote Architecture: amd64
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

## Chrome Log

```log
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=e5832578-2605-470f-a8e1-c885ea602bb0:2872 [TimeHooker] loading outer window...
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=e5832578-2605-470f-a8e1-c885ea602bb0:2357 Time Hooker Works!
log.ts:301  INFO [Service Worker] registered
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=e5832578-2605-470f-a8e1-c885ea602bb0:2877 [TimeHooker] loading inner window...
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
（匿名） @ content_script.js:240
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at chrome-extension://bgbbfnhficapockahamfncjdialfcbgp/content_script.js:240:28
（匿名） @ content_script.js:240
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
​ [TimeHooker] loading inner window...
​ Blocked script execution in 'https://localhost:8765/webview/extensionEditor/fake.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
s @ content.js:105
sendToId @ content.js:106
（匿名） @ content.js:110
u @ content.js:110
（匿名） @ content.js:111
m @ content.js:111
w @ content.js:129
I @ content.js:132
（匿名） @ content.js:132
（匿名） @ content.js:132
（匿名） @ content.js:132
:8765/webview/extensionEditor/fake.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9:1 Blocked script execution in 'https://localhost:8765/webview/extensionEditor/fake.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
log.ts:313   ERR Error received from starting extension host (kind: Remote)
log.ts:313   ERR The remote extenion host took longer than 60s to send its ready message.
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 10 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
​ Blocked script execution in 'https://localhost:8765/webview/extensionEditor/fake.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
s @ content.js:105
sendToId @ content.js:106
（匿名） @ content.js:110
u @ content.js:110
（匿名） @ content.js:111
m @ content.js:111
w @ content.js:129
I @ content.js:132
（匿名） @ content.js:132
（匿名） @ content.js:132
（匿名） @ content.js:132
:8765/webview/extensionEditor/index.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Flocalhost%3A8765:1 Blocked script execution in 'https://localhost:8765/webview/extensionEditor/index.html?id=3dbcd463-2f44-4463-b2a0-b438364633a9&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Flocalhost%3A8765' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 10 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 10 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 10 seconds before reconnecting...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (workbench.web.api.js:584:40618)
    at s._timeout (workbench.web.api.js:584:40564)
    at workbench.web.api.js:584:40306
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
    at workbench.web.api.js:584:40024
    at l.fire (workbench.web.api.js:69:1712)
    at M.cancel (workbench.web.api.js:69:15007)
    at S.cancel (workbench.web.api.js:69:15548)
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] waiting for 10 seconds before reconnecting...
DevTools 无法加载来源映射：无法加载 https://localhost:8765/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/serviceWorker.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://localhost:8765/static/node_modules/@vscode/vscode-languagedetection/dist/lib/index.js.map 的内容：Fetch through target failed: Target not supported; Fallback: HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 chrome-extension://dobbfkjhgbkmmcooahlnllfopfmhcoln/scripts/contentscript.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][8e95b…][reconnect] connecting to localhost:8765...
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect][localhost:8765] received error control message when negotiating connection. Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:732:17)
    at remoteAgentConnection.ts:327:17
    at l.fire (event.ts:577:16)
    at u.fire (ipc.net.ts:511:19)
    at r._receiveMessage (ipc.net.ts:873:27)
    at ipc.net.ts:818:73
    at l.fire (event.ts:577:16)
    at d.acceptChunk (ipc.net.ts:284:21)
    at ipc.net.ts:245:51
    at browserSocketFactory.ts:197:39
log.ts:313   ERR [remote-connection][ExtensionHost][8e95b…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:732:17)
    at remoteAgentConnection.ts:327:17
    at l.fire (event.ts:577:16)
    at u.fire (ipc.net.ts:511:19)
    at r._receiveMessage (ipc.net.ts:873:27)
    at ipc.net.ts:818:73
    at l.fire (event.ts:577:16)
    at d.acceptChunk (ipc.net.ts:284:21)
    at ipc.net.ts:245:51
    at browserSocketFactory.ts:197:39
abstractExtensionService.ts:644 Extension host (Remote) terminated unexpectedly. Code: 0, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:644
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:636
（匿名） @ abstractExtensionService.ts:626
fire @ event.ts:577
_onExtHostConnectionLost @ remoteExtensionHost.ts:209
（匿名） @ remoteExtensionHost.ts:137
fire @ event.ts:577
fire @ ipc.net.ts:511
acceptDisconnect @ ipc.net.ts:838
F @ remoteAgentConnection.ts:721
_gotoPermanentFailure @ remoteAgentConnection.ts:680
（匿名） @ remoteAgentConnection.ts:524
triggerPermanentFailure @ remoteAgentConnection.ts:524
_runReconnectingLoop @ remoteAgentConnection.ts:636
```

### Expected

default

### Actual

error

### Logs

```bash
docker logs code-server
```

```log
[2022-03-03T16:21:07.256Z] info  code-server 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
[2022-03-03T16:21:07.257Z] info  Using user-data-dir ~/.local/share/code-server
[2022-03-03T16:21:07.280Z] info  Using config file ~/.config/code-server/config.yaml
[2022-03-03T16:21:07.280Z] info  HTTPS server listening on https://0.0.0.0:8765/
[2022-03-03T16:21:07.280Z] info    - Authentication is enabled
[2022-03-03T16:21:07.280Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-03-03T16:21:07.281Z] info    - Using certificate for HTTPS: ~/.local/share/code-server/localhost.crt
[00:21:12] Extension host agent started.
[00:21:21] [172.17.0.1][9bcef417][ManagementConnection] New connection established.
[00:21:22] [172.17.0.1][782cf6d5][ExtensionHostConnection] New connection established.
[00:21:22] [172.17.0.1][782cf6d5][ExtensionHostConnection] <96> Launched Extension Host Process.
[00:21:42] [172.17.0.1][782cf6d5][ExtensionHostConnection] The client has reconnected.
[00:22:02] [172.17.0.1][782cf6d5][ExtensionHostConnection] The client has reconnected.
[00:22:22] [172.17.0.1][782cf6d5][ExtensionHostConnection] The client has reconnected.
[00:22:22] [172.17.0.1][782cf6d5][ExtensionHostConnection] <96> Extension Host Process exited with code: 0, signal: null.
[00:22:42] [172.17.0.1][782cf6d5][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:22:42] [172.17.0.1][9bcef417][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[00:24:30] [172.17.0.1][eb466207][ManagementConnection] New connection established.
[00:24:30] [172.17.0.1][e4776355][ExtensionHostConnection] New connection established.
[00:24:30] [172.17.0.1][e4776355][ExtensionHostConnection] <183> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 44 chars and 1 size events
[2022-03-03T16:24:46.049Z] error child:36 Uncaught exception: EISDIR: illegal operation on a directory, read
[2022-03-03T16:24:46.049Z] error child:36 Error: EISDIR: illegal operation on a directory, read
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[00:24:51] [172.17.0.1][e4776355][ExtensionHostConnection] The client has reconnected.
[00:25:05] Installing extension: ms-ceintl.vscode-language-pack-zh-hans
[00:25:11] [172.17.0.1][e4776355][ExtensionHostConnection] The client has reconnected.
[00:25:17] Downloaded extension: ms-ceintl.vscode-language-pack-zh-hans /root/.local/share/code-server/CachedExtensionVSIXs/ms-ceintl.vscode-language-pack-zh-hans-1.63.3
[00:25:17] Extracted extension to /root/.local/share/code-server/extensions/.c3cf3be9-06a3-4ee6-9cd6-b65fd7471804: ms-ceintl.vscode-language-pack-zh-hans
[00:25:17] Renamed to /root/.local/share/code-server/extensions/ms-ceintl.vscode-language-pack-zh-hans-1.63.3
[00:25:17] Extracting completed. ms-ceintl.vscode-language-pack-zh-hans
[00:25:17] Adding language packs from the extension ms-ceintl.vscode-language-pack-zh-hans
[00:25:17] Extension installed successfully: ms-ceintl.vscode-language-pack-zh-hans
[00:25:21] [172.17.0.1][eb466207][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[00:25:22] [172.17.0.1][2607610c][ManagementConnection] New connection established.
[00:25:22] [172.17.0.1][3499eaba][ExtensionHostConnection] New connection established.
[00:25:22] [172.17.0.1][3499eaba][ExtensionHostConnection] <218> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 44 chars and 1 size events
[00:25:31] [172.17.0.1][e4776355][ExtensionHostConnection] <183> Extension Host Process exited with code: 0, signal: null.
[00:25:43] [172.17.0.1][3499eaba][ExtensionHostConnection] The client has reconnected.
[00:26:03] [172.17.0.1][3499eaba][ExtensionHostConnection] The client has reconnected.
[00:26:23] [172.17.0.1][3499eaba][ExtensionHostConnection] The client has reconnected.
[00:26:23] [172.17.0.1][3499eaba][ExtensionHostConnection] <218> Extension Host Process exited with code: 0, signal: null.
[00:26:43] [172.17.0.1][3499eaba][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:26:43] [172.17.0.1][2607610c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[00:26:44] Installing extension: cschleiden.vscode-github-actions
[2022-03-03T16:26:45.966Z] error child:36 Uncaught exception: EISDIR: illegal operation on a directory, read
[2022-03-03T16:26:45.968Z] error child:36 Error: EISDIR: illegal operation on a directory, read
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[00:26:46] [172.17.0.1][eafc0ad7][ManagementConnection] New connection established.
[00:26:46] [172.17.0.1][58b29754][ExtensionHostConnection] New connection established.
[00:26:46] [172.17.0.1][58b29754][ExtensionHostConnection] <242> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 44 chars and 1 size events
[00:27:04] Extensions is already requested to install cschleiden.vscode-github-actions
[00:27:07] [172.17.0.1][58b29754][ExtensionHostConnection] The client has reconnected.
[00:27:27] [172.17.0.1][58b29754][ExtensionHostConnection] The client has reconnected.
[00:27:47] [172.17.0.1][58b29754][ExtensionHostConnection] The client has reconnected.
[00:27:47] [172.17.0.1][58b29754][ExtensionHostConnection] <242> Extension Host Process exited with code: 0, signal: null.
[00:28:07] [172.17.0.1][58b29754][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:28:07] [172.17.0.1][eafc0ad7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[00:28:44] [172.17.0.1][170d37f5][ManagementConnection] New connection established.
[00:28:45] [172.17.0.1][8e95bc04][ExtensionHostConnection] New connection established.
[00:28:45] [172.17.0.1][8e95bc04][ExtensionHostConnection] <266> Launched Extension Host Process.
[2022-03-03T16:28:45.920Z] error child:36 Uncaught exception: EISDIR: illegal operation on a directory, read
[2022-03-03T16:28:45.920Z] error child:36 Error: EISDIR: illegal operation on a directory, read
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 44 chars and 1 size events
[00:29:40] Extensions is already requested to install cschleiden.vscode-github-actions
[00:29:45] [172.17.0.1][8e95bc04][ExtensionHostConnection] <266> Extension Host Process exited with code: 0, signal: null.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
[2022-03-03T16:30:45.829Z] error child:36 Uncaught exception: EISDIR: illegal operation on a directory, read
[2022-03-03T16:30:45.829Z] error child:36 Error: EISDIR: illegal operation on a directory, read
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
[00:31:20] [172.17.0.1][8e95bc04][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:31:20] [172.17.0.1][170d37f5][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
[00:33:30] [172.17.0.1][2af929db][ManagementConnection] New connection established.
[00:33:31] [172.17.0.1][60dfa753][ExtensionHostConnection] New connection established.
[00:33:31] [172.17.0.1][60dfa753][ExtensionHostConnection] <526> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 874 chars and 1 size events
[00:33:51] [172.17.0.1][60dfa753][ExtensionHostConnection] The client has reconnected.
[00:34:12] [172.17.0.1][60dfa753][ExtensionHostConnection] The client has reconnected.
[00:34:31] [172.17.0.1][60dfa753][ExtensionHostConnection] <526> Extension Host Process exited with code: 0, signal: null.
[00:34:33] [172.17.0.1][60dfa753][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:34:33] [172.17.0.1][2af929db][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[00:35:05] [172.17.0.1][1a4c5345][ManagementConnection] New connection established.
[00:35:06] [172.17.0.1][12bf495a][ExtensionHostConnection] New connection established.
[00:35:06] [172.17.0.1][12bf495a][ExtensionHostConnection] <550> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 874 chars and 1 size events
[00:35:27] [172.17.0.1][12bf495a][ExtensionHostConnection] The client has reconnected.
[00:35:48] [172.17.0.1][12bf495a][ExtensionHostConnection] The client has reconnected.
[00:35:50] Downloaded extension: cschleiden.vscode-github-actions /root/.local/share/code-server/CachedExtensionVSIXs/cschleiden.vscode-github-actions-0.22.0
[00:35:51] Extracted extension to /root/.local/share/code-server/extensions/.fc7bea2f-9c0a-4daa-ba99-f2c6d1abb83c: cschleiden.vscode-github-actions
[00:35:51] Renamed to /root/.local/share/code-server/extensions/cschleiden.vscode-github-actions-0.22.0
[00:35:51] Extracting completed. cschleiden.vscode-github-actions
[00:35:51] Extension installed successfully: cschleiden.vscode-github-actions
[00:36:07] [172.17.0.1][12bf495a][ExtensionHostConnection] <550> Extension Host Process exited with code: 0, signal: null.
[00:36:09] [172.17.0.1][12bf495a][ExtensionHostConnection] Unknown reconnection token (seen before).
[00:36:09] [172.17.0.1][1a4c5345][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
```

### Screenshot/Video

![image](https://user-images.githubusercontent.com/73819467/156609823-57e41d9a-091a-4539-88b8-088d7646a6d2.png)
![image](https://user-images.githubusercontent.com/73819467/156609901-8a1352ed-dc94-47b3-886e-836fe607abdd.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I've been so tired writing code lately

**Comment by XRSec** [comment]
@jsjoeio yes

**Comment by XRSec** [comment]
Install 2022 0303

**Comment by jsjoeio** [comment]
This looks similar to the reconnection error we fixed for the next release. Please hang tight and wait for 4.0.3

Then give it a try and let us know if this still happens!

**Comment by XRSec** [comment]
@jsjoeio Ask a question not about this product

Do you know of any idea/vscode plugins that can automatically switch input methods when writing code prompts?

Windows is shift switch, and Mac is control + space, And the Mac's input method switching feels a bit stuck

thanks very much 🙏

**Comment by jsjoeio** [comment]
@XRSec hmm I'm not sure I understand. Are we talking about language input switching? On MacOS, I use this in the top menu bar to switch inputs.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/3806031/156801297-2ffe7c9b-dc0f-4876-b8ae-e557f0603334.png">

On Windows, there is something in the bottom bar to do the same.

I don't know of any VS Code plugins that will do it automatically 🤔 I'm not sure if it would be have access to the system APIs to do that. 

The only other thing that comes to mind is binding it to a keyboard shortcut that feels the same across Windows/Mac. Maybe this will help? [Make Windows Like macOS](https://joeprevite.com/windows-like-macos)

**Comment by XRSec** [comment]
@jsjoeio I think it's a waste of time to stop and choose an input method when writing code, and it's also a waste of time if you're not used to using English as code comments, thank you for your reply

**Comment by XRSec** [comment]
// this is an code commit 
fmt.prinfln(this is commit)

**Comment by jsjoeio** [comment]
@XRSec I'm not sure I follow what you mean here by "switch the input method" - can you elaborate?

**Comment by jsjoeio** [comment]
Oh I think I understand now. I wish I could help but don't know of any options 🤔 Maybe you could write a custom VS Code extension though.

**Comment by XRSec** [comment]
@jsjoeio Long live to understand, this plug-in is too difficult to do, many similar plug-ins say that the interface is adjusted, such as path completion, code improvement, there is no reference project

**Comment by skyilz** [comment]
我同样出现了这种问题，请问您解决了吗？如果解决，能否分享下方法。
I have the same problem, have you solved it? If solved, can you share the method.

**Comment by XRSec** [comment]
@skyilz 等待更新，人家可能看不懂中文
