### ISSUE TITLE
[Bug]: Files missing from code-oss-dev/extensions/ipynb in MacOS Homebrew installation

### ISSUE THREAD

**Issue by quantex** [coder/code-server#4964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari 15.3
- Local OS: MacOS 12.2.1
- Remote OS: MacOS 12.2.1 and Arch Linux (rolling; 5.16.12).
- Remote Architecture: x86-64
- `code-server --version`: 4.1.0

### Steps to Reproduce

1. Install with HomeBrew via `brew install code-server`
2. Install extensions: Jupyter (ms-toolsai) and Python (ms-python)
3. Open or create a Jupyter Notebook.
4. Peruse Logs for Remote Extension Host

### Expected

A sequence of extensions (vscode.ipynb, then ms-toolsai.jupyter, then ms-python.python) should load, resulting in a Jupyter Notebook being rendered.

### Actual

This works as expected in an Arch Linux installation (via an AUR).

But on a MacOS Homebrew installation, this halts when trying to load vscode.ipynb. Log complains that `[install folder]/vendor/modules/code-oss-dev/extensions/ipynb/dist/ipynbMain.js` is missing. A side-effect of this is simply that the Jupyter Notebook fails to load (or a new Notebook fails to be created).

A band-aid fix is to simply copy over `[folder]/vendor/modules/code-oss-dev/extensions/ipynb/` wholesale from a working code-server installation in an Arch Linux box, which appears to resolve the problem.

### Logs
```
  [2022-03-09 05:12:21.415] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebook:jupyter-notebook}'
  [2022-03-09 05:12:21.418] [exthost] [error] Activating extension vscode.ipynb failed due to an error:
  [2022-03-09 05:12:21.418] [exthost] [error] Error: Cannot find module '/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/extensions/ipynb/dist/ipynbMain.js'
  Require stack:
  - /Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/loader.js
  - /Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-amd.js
  - /Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-fork.js
	  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
	  at Function.Module._load (internal/modules/cjs/loader.js:746:27)
	  at Function.t._load (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:28641)
	  at Function.g._load (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:25198)
	  at Function.f._load (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:104:61699)
	  at Module.require (internal/modules/cjs/loader.js:974:19)
	  at Module.require (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/extensions/git/dist/main.js:2:516200)
	  at require (internal/modules/cjs/helpers.js:101:18)
	  at Function.r [as __$__nodeRequire] (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/loader.js:5:101)
	  at p._loadCommonJSModule (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:26716)
	  at p._doActivateExtension (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:100:12954)
	  at p._activateExtension (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:100:11927)
	  at Object.actualActivateExtension (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:100:9302)
	  at b._activateExtension (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:7855)
	  at /Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:7537
	  at Array.map (<anonymous>)
	  at b._activateExtensions (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:7525)
	  at b.activateById (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:5123)
	  at p._activateById (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:100:10304)
	  at p.$activate (/Users/edrazor/brew/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:100:20813)
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Thanks fo reporting this! I was able to reproduce on my macOS.

## Video

https://user-images.githubusercontent.com/3806031/157534544-a7914067-febc-4a22-b545-e096d1660495.mov

## Browser Logs

```javascript
mainThreadExtensionService.ts:95 Activating extension 'vscode.ipynb' failed: Cannot find module '/usr/local/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/extensions/ipynb/dist/ipynbMain.js'
Require stack:
- /usr/local/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/loader.js
- /usr/local/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /usr/local/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-fork.js.

CRITI FAILED to destory notebook Error: NO provider registered for view type: 'jupyter-notebook'
    at O.withNotebookDataProvider (notebookServiceImpl.ts:611:10)
    at async u.createReferencedObject (notebookEditorModelResolverServiceImpl.ts:64:16)
    at async a.resolve (notebookEditorModelResolverServiceImpl.ts:216:18)
    at async l.$tryCreateNotebook (mainThreadNotebookDocuments.ts:131:15)
```

Here is where the corresponding code lives: https://github.com/coder/vscode/tree/main/extensions/ipynb 

I wonder if we missed something there. I did just upgrade us to 1.64 (when [this PR](https://github.com/coder/code-server/pull/4902) is merged).

**Comment by jsjoeio** [comment]
@quantex are you able to verify if this is still an issue with 4.2.0?
