### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by nuc-uriel** [coder/code-server#4988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrone
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: arm64
- `code-server --version`: 4.1.0

### Steps to Reproduce

1. open code-server
2. create a markdown file
3. Click Preview
4. is empty

### Expected

show markdown Preview

### Actual

empty

### Logs

[Extension Host] Server: {  "Commands": [    "gopls.add_dependency",    "gopls.add_import",    "gopls.apply_fix",    "gopls.check_upgrades",    "gopls.edit_go_directive",    "gopls.gc_details",    "gopls.generate",    "gopls.generate_gopls_mod",    "gopls.go_get_package",    "gopls.list_imports",    "gopls.list_known_packages",    "gopls.regenerate_cgo",    "gopls.remove_dependency",    "gopls.run_tests",    "gopls.start_debugging",    "gopls.test",    "gopls.tidy",    "gopls.toggle_gc_details",    "gopls.update_go_sum",    "gopls.upgrade_dependency",    "gopls.vendor"  ],  "Name": "gopls",  "Version": "v0.8.0",  "GoVersion": "go1.17.7"}
workbench.web.api.js:577   ERR Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at _.deserializeWebviewPanel (/usr/lib/code-server/vendor/modules/code-oss-dev/extensions/markdown-language-features/dist/extension.js:1:1280009)
	at n.$deserializeWebviewPanel (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:96:86788)
	at t._doInvokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13802)
	at t._invokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13486)
	at t._receiveRequest (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:12148)
	at t._receiveOneMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:10826)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:8922
	at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:30660
	at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
	at g._receiveMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:21237)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:18115
	at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at b.acceptChunk (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:13328)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:12676
	at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:19664
	at afterWrite (internal/streams/writable.js:466:5)
	at onwrite (internal/streams/writable.js:446:7)
	at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
	at Zlib.processCallback (zlib.js:608:8)
main.js:400 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at main.js:400:25
（匿名） @ main.js:400
main.js:204 Uncaught (in promise) Error: Service Workers are not enabled. Webviews will not work. Try disabling private/incognito mode.
    at main.js:204:17
    at new Promise (<anonymous>)
    at main.js:202:21
（匿名） @ main.js:204
（匿名） @ main.js:202

### Screenshot/Video

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/19432859/158105606-63d9971d-0216-404e-92b8-232e2bb661e9.png">

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by Vaibhav1919** [comment]
I am using version 4.12.0 and still getting this issue

**Comment by code-asher** [comment]
@Vaibhav1919 do you get the same "Service Workers are not enabled. Webviews will not work. Try disabling private/incognito mode." error?  Or different errors?

If you do get the same error make sure you are using HTTPS with a recent browser and not in private/incognito mode.

**Comment by Vaibhav1919** [comment]
I am getting the following error . @code-asher can you look into same ?
![image](https://github.com/coder/code-server/assets/90383614/54933e81-4792-461a-8cbc-978e5abf26d0)

**Comment by code-asher** [comment]
For anyone following along we are debugging this in https://github.com/coder/code-server/issues/6203
