### ISSUE TITLE
[Bug]: Activating extension 'vscjava.vscode-java-test' failed: Cannot read properties of undefined (reading 'name').

### ISSUE THREAD

**Issue by Avirup-301294** [coder/code-server#5200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 
- Remote OS: Ubuntu
- Remote Architecture: 
- `code-server --version`: 4.4.0

### Steps to Reproduce

This seems not a bug completely, but a crash, sometimes get this when loading some spring Gradle project, where I already have installed the java extensions pack. Don't know why I am getting this. Previously I used code-server version 3.4.1 with an older version of the Java Extension pack and now I updated the versions and getting this. 

### Expected

Due to this crash the Java Test runner (Beaker Icon is not loading and I am not able to test my spring project). Expected behaviour should be load the test runner.

### Actual

The Beaker Icon on the left navigation pane is not showing even though the project is completely loaded and shown in Java Projects section.

### Screenshot/Video

![image](https://user-images.githubusercontent.com/45994215/168207216-f4996917-ef2d-43b4-9f9e-4e0a526e8929.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you please update Steps to Reproduce with a list 1,2,3 etc. That'll help us triage this faster.

**Comment by Avirup-301294** [comment]
1. On the steps to reproduce, it is not consistent - so unable to get clear repro steps.
2. When this happens next time, would you want us to look into some log files specifically and share it?

**Comment by jsjoeio** [comment]
Ah okay. Yes, if you could open the DevTools and look at the browser console logs, that might help. And any logs you see on the server where code-server is running. Thanks!

**Comment by krishnabharathi1997** [comment]
## We have found a repro for this problem

### Note:

We are launching a code-server in an AWS virtual machine.

### Issue
 When we try to open or reload the code server with a java file (.java) opened. The extension crashes and throws - “**Activating vscjava.vscode-java-test extension failed**” . But if we reload with a non-java file opened (.json/.txt). The extension loads correctly and works without any other problem.

We tried to find the logs during the failure case. It clearly says some execution error during extension activation.

**Log path** - `/home/crio-user/.local/share/code-server/logs/20220518T103013/exthost2/exhost.log`

```
[2022-05-19 17:33:44.611] [exthost] [error] Activating extension vscjava.vscode-java-test failed due to an error:
[2022-05-19 17:33:44.611] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'name')
	at t.fromCallback (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:597697)
	at Object.7749 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:370379)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.5674 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:371122)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.1708 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:557865)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.8120 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:542103)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.8735 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:547940)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.8633 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:534763)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.112 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:564672)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at Object.8786 (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:526725)
	at n (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815234)
	at /home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815665
	at Object.<anonymous> (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/dist/extension.bundle.js:2:815691)
	at Module._compile (node:internal/modules/cjs/loader:1105:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.i._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:104:32278)
	at Function.m._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:104:28763)
	at Function.g._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/home/crio-user/.local/share/code-server/extensions/vscjava.vscode-java-test-0.35.0/main.js:8:19)
	at Module._compile (node:internal/modules/cjs/loader:1105:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.i._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:104:32278)
	at Function.m._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:104:28763)
	at Function.g._load (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as _$_nodeRequire] (/opt/lib/vscode/out/vs/loader.js:5:101)
	at E._loadCommonJSModule (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:104:30440)
	at E._doActivateExtension (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:90:13361)
	at E._activateExtension (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:90:12313)
	at Object.actualActivateExtension (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:90:9469)
	at g._activate (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:85:8171)
	at g._waitForDepsThenActivate (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:85:8107)
	at async g._initialize (/opt/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)
```


Have attached a video recording below for reproducing the problem.

**Link** - https://www.loom.com/share/1c9878462fb6460ba29355abd2c6d750

### As we are facing this problem in the production systems, requesting the team to fix the problem asap.

**Comment by Avirup-301294** [comment]
> Ah okay. Yes, if you could open the DevTools and look at the browser console logs, that might help. And any logs you see on the server where code-server is running. Thanks!

You can refer @krishnabharathi1997 update. We work in the same team.

**Comment by jsjoeio** [comment]
Thanks y'all! I will take a look on Monday and see if I can reproduce this locally. Appreciate the Loom too!

**Comment by jsjoeio** [comment]
Okay so I tried reproducing it but I'm not getting the same error.

## Video

https://www.loom.com/share/a4f6746784ef4806a6698120361e4a4a

## Screenshot
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/169915521-4fa0199c-0e0d-4484-ade0-73957d9f0d87.png">

## Resources for myself

- https://www.programiz.com/java-programming/hello-world
- https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack
- https://code.visualstudio.com/docs/java/java-tutorial#_coding-pack-for-java

**Comment by Avirup-301294** [comment]
Thanks, @jsjoeio for investigating our issue.


We have some Gradle projects with multiple dependencies, so when we try to build the Gradle or reload the code-server while keeping any .java file open usually takes around 1min to complete. So at the same time if the java test runner loads and tries to activate before the Gradle build complete, then we are facing this java test runner activation issue. 

So we are guessing there is some synchronisation issue between the extension activation time and the project loading/Gradle build time. So we have identified solid steps to reproduce the issue.

If possible we can get on a call so that we can show a live reproduction or we can share our own infra setup (Running VM) with you privately (Email), so that you can even try to reproduce it yourself.

As we are facing this issue in the production system, we are looking forward to your response, so it will increase the chances of identifying and resolving the issue quickly.

**Comment by jsjoeio** [comment]
> So we are guessing there is some synchronisation issue between the extension activation time and the project loading/Gradle build time.

If that's the case, would it make sense to open an issue with the team that owns this extension? I feel like they would be able to help more than me.

Can this be reproduced in Codespaces by chance?

**Comment by Avirup-301294** [comment]
Thanks @jsjoeio, 

I have made a workaround in the issue. Working nicely with Code Server v4.4. I disable the updates for extensions and install older extension for test runner and now its working fice. No bugs and nothing. 

Closing this thread! This is solved!
