### ISSUE TITLE
[Bug]: Unable to access server due to timeout and Zlib problem

### ISSUE THREAD

**Issue by devonhumes** [coder/code-server#5235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macos
- Remote OS: macos 12.4
- Remote Architecture: darwin-x64
- `code-server --version`: 4.4.0

Also:

- Web Browser: Safari
- Local OS: macos
- Remote OS: iOS 15.5
- Remote Architecture: pre-m1
- `code-server --version`: 4.4.0

I'm u 

### Steps to Reproduce

1. Install `code-server` using install script (this uses homebrew)
2. Run code server (the same thing happens if I start using `brew servers` or manually using `code-server`)

### Expected

Accessing the webpage should load successfully

### Actual

The page loads, but the request times out and the page load fails to complete.

This error is shown:

![image](https://user-images.githubusercontent.com/693754/171230635-40896ca7-eb74-4518-a573-4fd2ad0bb7fa.png)

### Logs

# Code Server Logs

```
[2022-05-31T16:51:50.706Z] trace child:4171 got message {"message":{"type":"handshake","args":{"bind-addr":"127.0.0.1:8080","auth":"password","password":"<redacted>","config":"/Users/<redacted>/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/Users/<redacted>/.local/share/code-server","extensions-dir":"/Users/<redacted>/.local/share/code-server/extensions","log":"trace","host":"127.0.0.1","port":8080,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
[2022-05-31T16:51:50.708Z] info  code-server 4.4.0 b088ec7adf9e17bc75215f79e21498eb40da03ed
[2022-05-31T16:51:50.708Z] info  Using user-data-dir ~/.local/share/code-server
[2022-05-31T16:51:50.708Z] trace Using extensions-dir ~/.local/share/code-server/extensions
[2022-05-31T16:51:50.719Z] info  Using config file ~/.config/code-server/config.yaml
[2022-05-31T16:51:50.719Z] info  HTTP server listening on http://127.0.0.1:8080/
[2022-05-31T16:51:50.719Z] info    - Authentication is enabled
[2022-05-31T16:51:50.719Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-05-31T16:51:50.719Z] info    - Not serving HTTPS
[2022-05-31T16:52:05.726Z] trace heartbeat
[09:52:05] Remote configuration data at /Users/<redacted>/.local/share/code-server
[09:52:05] process arguments: {
  'bind-addr': '127.0.0.1:8080',
  auth: 'password',
  password: '<redacted>',
  config: '/Users/<redacted>/.config/code-server/config.yaml',
  verbose: true,
  'user-data-dir': '/Users/<redacted>/.local/share/code-server',
  'extensions-dir': '/Users/<redacted>/.local/share/code-server/extensions',
  log: 'trace',
  host: '127.0.0.1',
  port: '8080',
  'proxy-domain': [],
  _: [],
  usingEnvPassword: false,
  usingEnvHashedPassword: false,
  'accept-server-license-terms': true,
  compatibility: '1.64',
  help: false,
  version: false,
  'without-connection-token': true,
  'without-browser-env-var': true,
  'builtin-extensions-dir': '/usr/local/Cellar/code-server/4.4.0/libexec/lib/vscode/extensions',
  logsPath: '/Users/<redacted>/.local/share/code-server/logs/20220531T095205'
}
[09:52:05] Started scanning system extensions
[09:52:05] Started scanning user extensions
[09:52:05] resolveShellEnv(): running (macOS/Linux)
[09:52:05] getUnixShellEnvironment#runAsNode undefined
[09:52:05] getUnixShellEnvironment#noAttach undefined
[09:52:05] getUnixShellEnvironment#env {
<redacted>
}
[09:52:05] ComputeTargetPlatform: darwin-x64
[09:52:05] getUnixShellEnvironment#shell /bin/zsh
[09:52:05] getUnixShellEnvironment#spawn ["-ilc"] '/usr/local/Cellar/node@16/16.15.0/bin/node'  -p '"63b289d731d5" + JSON.stringify(process.env) + "63b289d731d5"'
[09:52:05] Extension host agent started.
[09:52:05] [File Watcher (node.js)] Request to start watching: /Users/<redacted>/.local/share/code-server/Machine (excludes: <none>),/Users/<redacted>/.local/share/code-server/Machine/settings.json (excludes: <none>),/Users/<redacted>/.local/share/code-server/extensions (excludes: <none>)
[09:52:05] Extension VSIX downlads cache dir does not exist
[09:52:05] Scanned user extensions: 0
[09:52:05] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/<redacted>/.local/share/code-server/Machine/settings.json'
[09:52:05] [File Watcher (node.js)] Started watching: '/Users/<redacted>/.local/share/code-server/Machine'
[09:52:05] [File Watcher (node.js)] Started watching: '/Users/<redacted>/.local/share/code-server/extensions'
[09:52:06] Scanned system extensions: 88
Error: invalid code lengths set
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
[09:52:06] Error: invalid code lengths set
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
[09:52:07] getUnixShellEnvironment#raw 63b289d731d5 <redacted> 63b289d731d5

[09:52:07] getUnixShellEnvironment#result {
<redacted>
}
[2022-05-31T16:52:17.202Z] debug got latest version {"latest":"4.4.0"}
[2022-05-31T16:52:17.203Z] debug comparing versions {"current":"4.4.0","latest":"4.4.0"}
Error: invalid code lengths set
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
[09:52:17] Error: invalid code lengths set
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

# Browser Console Logs

```
 ERR [remote-connection][Management   ][b2681…][initial][<redacted>:8887] the handshake timed out. Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (remoteAgentConnection.ts:152:20)
    at s._timeout (remoteAgentConnection.ts:148:28)
    at remoteAgentConnection.ts:130:86
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at R.cancel (cancellation.ts:69:19)
    at k.cancel (cancellation.ts:124:16)
    at remoteAgentConnection.ts:103:41
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
log.ts:313   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (remoteAgentConnection.ts:152:20)
    at s._timeout (remoteAgentConnection.ts:148:28)
    at remoteAgentConnection.ts:130:86
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at R.cancel (cancellation.ts:69:19)
    at k.cancel (cancellation.ts:124:16)
    at remoteAgentConnection.ts:103:41
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
log.ts:313   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Time limit reached
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/settings.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (remoteAgentConnection.ts:152:20)
    at s._timeout (remoteAgentConnection.ts:148:28)
    at remoteAgentConnection.ts:130:86
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at R.cancel (cancellation.ts:69:19)
    at k.cancel (cancellation.ts:124:16)
    at remoteAgentConnection.ts:103:41
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
log.ts:313   ERR Error: Time limit reached
    at s._createTimeoutError (remoteAgentConnection.ts:152:20)
    at s._timeout (remoteAgentConnection.ts:148:28)
    at remoteAgentConnection.ts:130:86
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at R.cancel (cancellation.ts:69:19)
    at k.cancel (cancellation.ts:124:16)
    at remoteAgentConnection.ts:103:41
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
webWorkerExtensionHost.ts:111 The web worker extension host is started in a same-origin iframe!
_getWebWorkerExtensionHostIframeSrc @ webWorkerExtensionHost.ts:111
_startInsideIframe @ webWorkerExtensionHost.ts:127
start @ webWorkerExtensionHost.ts:120
Pr @ extensionHostManager.ts:132
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
n @ extensionHostManager.ts:63
_createExtensionHostManager @ abstractExtensionService.ts:863
_startExtensionHostsIfNecessary @ abstractExtensionService.ts:849
_initialize @ abstractExtensionService.ts:743
(anonymous) @ extensionService.ts:79
Promise.then (async)
Ml @ extensionService.ts:77
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ web.main.ts:105
await in open (async)
a @ web.factory.ts:61
(anonymous) @ workbench.ts:500
(anonymous) @ workbench.ts:507
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:8
(anonymous) @ fake:1
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/keybindings.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
2log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/systemExtensionsCache.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/extensions.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/systemExtensionsCache.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/extensions.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/systemExtensionsCache.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/extensions.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:301  INFO Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/extensions.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
log.ts:301  INFO [Service Worker] registered
log.ts:313   ERR Time limit reached: Error: Time limit reached
    at s._createTimeoutError (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44635)
    at s._timeout (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44581)
    at https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44323
    at S.invoke (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:145)
    at s.fire (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:1856)
    at R.cancel (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:15702)
    at k.cancel (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:16243)
    at https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44041
    at S.invoke (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:145)
    at s.fire (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:1856)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/settings.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/tasks.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.doWatch (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40466)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:40332
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/settings.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:10563
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async resolveContents (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:10836)
    at async r.loadConfiguration (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:11049)
    at async l.reload (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:9109)
    at async O.reloadLocalUserConfiguration (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:2639:33156)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/tasks.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:10563
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async resolveContents (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:10836)
    at async r.loadConfiguration (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:11049)
    at async l.reload (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:1333:9109)
    at async O.reloadLocalUserConfiguration (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:2639:33156)
DevTools failed to load source map: Could not load content for https://<redacted>:8887/vs/workbench/api/worker/extensionHostWorker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://<redacted>:8887/vs/workbench/api/worker/extensionHostWorker.nls.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
log.ts:313   ERR Time limit reached: Error: Time limit reached
    at s._createTimeoutError (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44635)
    at s._timeout (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44581)
    at https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44323
    at S.invoke (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:145)
    at s.fire (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:1856)
    at R.cancel (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:15702)
    at k.cancel (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:16243)
    at https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:617:44041
    at S.invoke (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:145)
    at s.fire (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:67:1856)
log.ts:313   ERR ENOPRO: No file system provider found for resource 'vscode-remote:/Users/<redacted>/.local/share/code-server/User/systemExtensionsCache.json'
    at g.withProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26704)
    at async g.withReadProvider (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:26827)
    at async g.readFile (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:610:31385)
    at async Object.factory (https://<redacted>:8887/static/out/vs/workbench/workbench.web.main.js:3118:116033)
```

### Screenshot/Video

![image](https://user-images.githubusercontent.com/693754/171254412-bd7689e4-7b4d-4f00-a38a-c0cdef59f0d1.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This is my very first time trying to run code-server and I might be missing something really obvious, but I can't find any issue or Google search that answers my question.

**I AM NOT USING HTTPS** I could not submit the form without selecting that option.

**Comment by devonhumes** [comment]
This appears to be an issue with using Caddy. The caddy instance is not correctly forwarding the requests. It would be helpful for the docs to be updated. I tried to figure out what was wrong and I tested using the same settings for Nginx, but it didn't work.

**Comment by jsjoeio** [comment]
>  It would be helpful for the docs to be updated 
@devonhumes PRs welcome!
