### ISSUE TITLE
[Bug]: Error: Unable to retrieve document from URI

### ISSUE THREAD

**Issue by 502647092** [coder/code-server#5552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge 105.0.1343.27
- Local OS: Windows
- Remote OS: CentOs7
- Remote Architecture: amd64
- `code-server --version`:
```
1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64
```

### Steps to Reproduce

1. open code-server
2. open php file
3. format file

### Expected

format file

### Actual

nothing

### Logs

have error at devtools console
```
 WARN Error: Unable to retrieve document from URI 'file:///home/wwwroot/shop.pterodactyl.love/modules/servers/pterodactyl/lib/PterodactylClient.php'
	at k.getDocument (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:87:11047)
	at D.$participateInSave (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:83:31956)
	at i._doInvokeHandler (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:13689)
	at i._invokeHandler (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:13371)
	at i._receiveRequest (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:12141)
	at i._receiveOneMessage (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:10843)
	at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:8950
	at b.invoke (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:145)
	at p.deliver (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2266)
	at v.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1844)
	at o.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:19042)
	at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
	at b.invoke (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:145)
	at p.deliver (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2266)
	at v.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1844)
	at o.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:19042)
	at r._receiveMessage (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:23854)
	at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:22874
	at b.invoke (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:145)
	at p.deliver (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2266)
	at v.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1844)
	at v.acceptChunk (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:15873)
	at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:15003
	at b.invoke (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:145)
	at p.deliver (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2266)
	at v.fire (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1844)
	at v._processReadQueue (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:68:34245)
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Which version of `code-server` are you using? `code-server --version` will tell you.

**Comment by 502647092** [comment]
> Which version of `code-server` are you using? `code-server --version` will tell you.

1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64

**Comment by jsjoeio** [comment]
That doesn't tell me which code-server version. Are you sure you're looking at the right project?

**Comment by 502647092** [comment]
> That doesn't tell me which code-server version. Are you sure you're looking at the right project?

code-server: v4.7.0

**Comment by jsjoeio** [comment]
Thanks! Which extension are you using for your PHP formatter?

**Comment by 502647092** [comment]
junstyle.php-cs-fixer

**Comment by jsjoeio** [comment]
Thank you! Are you able to record a video showing what happens after you install the extension and format the document? I want to make sure I'm following the same steps.
