### ISSUE TITLE
[Bug]: Screen keeps white 

### ISSUE THREAD

**Issue by dayaftereh** [coder/code-server#5631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: 106.0.5249.79 (Offizieller Build) (32-Bit) 
- Local OS: Android 12; SM-T505 Build/SP1A.210812.016
- Remote OS: termux: Linux localhost 5.4.0-faked #1 SMP PREEMPT Thu Jul 21 13:37:12 +07 2022 aarch64 GNU/Linux
- Remote Architecture: arm64
- `code-server --version`:  4.7.0 7f108c61ab670ccaae4cfde5de2909c003db1ce8 with Code 1.71.0

### Steps to Reproduce

1. Install via nvm described in code-server/termux.md
2. Starting `code-server`
3. Open chrome at https://127.0.0.1:8080

### Expected

Code-server should open the workspace

### Actual

The screen keeps to be white. 

### Logs

```
root@localhost:~# code-server --log trace
Trace: [2022-10-08T21:17:07.273Z] trace child:23950 got message {"message":{"type":"handshake","args":{"bind-addr":"127.0.0.1:8080","auth":"none","password":"d0ae68507ed5a51da70b41d2","cert":{"value":"/root/.local/share/code-server/localhost.crt"},"cert-key":"/root/.local/share/code-server/localhost.key","config":"/root/.config/code-server/config.yaml","log":"trace","user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","verbose":true,"host":"127.0.0.1","port":8080,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
    at doLog (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:57:28)
    at ServerFormatter.doWrite (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:204:9)
    at ServerFormatter.write (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:119:14)
    at Logger.handle (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:339:25)
    at Logger.trace (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:268:14)
    at process.onMessage (/usr/lib/code-server/out/node/wrapper.js:72:47)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[2022-10-08T21:17:07.291Z] info  code-server 4.7.0 7f108c61ab670ccaae4cfde5de2909c003db1ce8
[2022-10-08T21:17:07.292Z] info  Using user-data-dir ~/.local/share/code-server
Trace: [2022-10-08T21:17:07.292Z] trace Using extensions-dir ~/.local/share/code-server/extensions
    at doLog (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:57:28)
    at ServerFormatter.doWrite (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:200:20)
    at ServerFormatter.write (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:119:14)
    at Logger.handle (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:339:25)
    at Logger.trace (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:268:14)
    at /usr/lib/code-server/out/node/main.js:121:21
    at Generator.next (<anonymous>)
    at /usr/lib/code-server/out/node/main.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/code-server/out/node/main.js:27:12)
[2022-10-08T21:17:07.445Z] info  Using config file ~/.config/code-server/config.yaml
[2022-10-08T21:17:07.446Z] info  HTTPS server listening on https://127.0.0.1:8080/
[2022-10-08T21:17:07.446Z] info    - Authentication is disabled
[2022-10-08T21:17:07.446Z] info    - Using certificate for HTTPS: ~/.local/share/code-server/localhost.crt
```

### Screenshot/Video

![Screenshot_20221008-232326_Chrome](https://user-images.githubusercontent.com/12630268/194728260-27dfed3d-6f95-45fc-b3d8-19af8d93ae43.jpg)
![Unbenannt](https://user-images.githubusercontent.com/12630268/194728468-a88a6f3f-c2c1-42b2-a5ea-adf78b31bf17.png)
![Unbenannt2](https://user-images.githubusercontent.com/12630268/194728538-499d588c-e20f-4ccc-9f91-55368cfcc473.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I'm using code-server with termux on debian and installed as described in code-server/termux.md.

I open it on my android tablet ( SM-T505) but the screen keeps to be white. I connected a remote debugger, but the console is empty and all resources are loaded. 

Interesting is that code-server opens in a incognito window, but not in a normal frame or as pwa(added to start screen). I'm using a self signed certificate for https.

I also tried verion 4.7.1, but same result.

**Comment by jsjoeio** [comment]
What happens if you access vis HTTP?

**Comment by dayaftereh** [comment]
@jsjoeio I also tried HTTP, but with the same result, the screen keeps white. Maybe something with security, because in a incognito window everything works.

**Comment by dayaftereh** [comment]
I started the code-server with `--host 0.0.0.0` and opened the code-server with my android phone. The used chrome browser is the same `106.0.5249.79 (Offizieller Build) (32-Bit)` and every think works as expected.

**Comment by jsjoeio** [comment]
> The used chrome browser is the same 106.0.5249.79 (Offizieller Build) (32-Bit) and every think works as expected.

Interesting...well i'm happy you found a solution! Can we close this?

**Comment by jsjoeio** [comment]
Oh I misunderstood. Are there any logs in the Browser Console that you can share? I'm not sure about the white screen still 🤔

**Comment by code-asher** [comment]
I have no good theories but maybe open those network requests and 
make sure the content looks correct?  For example 
workbench.web.main.js, workbench.js, etc.

Since it works in incognito could also try checking that "disable 
cache" box in devtools just in case it is a caching issue.

If none of that helps it will just have to be debugged step by 
step by someone.

**Comment by dayaftereh** [comment]
I found no issue at all on loading and skipped using the table with code-server. I close the issue, maybe in the future someone find a solution.
