### ISSUE TITLE
[Bug]: Markdown Preview Failure because extensionHostWorker.js.map not found

### ISSUE THREAD

**Issue by Yobol** [coder/code-server#5934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu 22.04.4 LTS
- Remote OS: Ubuntu 22.04
- Remote Architecture:
- `code-server --version`: 4.9.1

Extra Information by 'Help -> About':
code-server: v4.9.1
Code: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-12-07T20:58:35.136Z (3 wks ago)
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Steps to Reproduce

1. create and open a markdown file, then input some contents
2. Click 'Open Preview to the side'

### Expected

Some contents show on the side preview panel.

### Actual

Nothing shows on the side preview panel.

### Logs

Open F12 Console:

```
log.ts:312  INFO Updating additional builtin extensions cache
log.ts:324   ERR Error while registering log channel vscode-log:/20221230T175238/remoteTunnel.log Timed out while waiting for file to be created
log.ts:324   ERR 'crypto.subtle' is not available so webviews will not work. This is likely because the editor is not running in a secure context (https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).: Error: 'crypto.subtle' is not available so webviews will not work. This is likely because the editor is not running in a secure context (https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).
    at t (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:820:22916)
    at new O (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:1395:5556)
    at n._createInstance (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:604:1522)
    at n.createInstance (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:604:947)
    at I.createWebviewElement (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:2336:44115)
    at b.show (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:1333:39272)
    at b.claim (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:1333:37561)
    at ja.claimWebview (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:1808:24033)
    at ja.setInput (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:1808:23944)
    at async a.doSetInput (http://172.16.30.4:32488/user/xxx/test/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/workbench/workbench.web.main.js:2771:6428)
```

PS: `http://172.16.30.4:32488/user/xxx/test` is base_url.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Why I must select all radioboxes? For example I just use HTTP.

**Comment by jsjoeio** [comment]
Can you try with HTTPS? Markdown Preview requires service workers which only work in secure contexts so that may fix it.

**Comment by Yobol** [comment]
Thanks a lot. I solved this problem with HTTPS.
