### ISSUE TITLE
All extensions disappeared in `4.10.0` and onwards after upgrading from `4.9.1`

### ISSUE THREAD

**Issue by bilogic** [coder/code-server#6108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chome
- Local OS: Windows 10 x64
- Remote OS: Ubuntu 22.04
- Remote Architecture:  x64
- `code-server --version`: 4.10.0

### Steps to Reproduce

1. Upgrade from 4.9.1 to 4.10.0
2. None of my extensions were loaded

### Expected

All my extensions should be loaded

### Actual

All my extensions did not load

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Any logs?  Does the problem persist if you reinstall the extensions?

**Comment by bilogic** [comment]
Not yet, it was a daily driver. I had to revert quickly. It basically went from 33 extensions to 0.

**Comment by hibrid** [comment]
This might be what I ran into and I had to re-install 1.76.2:

`ERR [Extension Host] Error: Error relocating /root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/node_modules/spdlog/build/Release/spdlog.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.g._load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:29906)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/node_modules/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.g._load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:29906)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at i (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:98)
    at n.load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:4:1651)
    at _.load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:3:9105)
    at u (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:9325)
    at Object.errorback (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:9444)
    at _.triggerErrorback (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:3:9399)
    at /root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:3:9150
    at n.load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:4:1668)
    at _.load (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:3:9105)
    at u (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:9325)
    at h._loadModule (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:9453)
    at h._resolve (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:6:452)
    at h.defineModule (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:5548)
    at h._relativeRequire (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:6172)
    at e (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/loader.js:5:8503)
    at L.C (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8815)
    at new Promise (<anonymous>)
    at L (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8795)
    at D.n (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9925)
    at new D (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9795)
    at A.m (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:106:954)
    at A.createLogger (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:5469)
    at new A (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:91:13841)
    at S.j (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:1296)
    at /root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3032
    at $.a (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48073)
    at $.get value [as value] (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48227)
    at Object.get (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3438)
    at new d (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:1150)
    at a (/root/.vscode-server-insiders/bin/d317fbf2970b8f28bd7c59f545c59532cd5b293c-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:34348)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by hibrid** [comment]
I can reproduce this consistently when I attach vscode to a running docker container. It started with 1.77

**Comment by bilogic** [comment]
@hibrid it is clearer use `code-server` version numbers, which one is 1.76.2 and which is 1.77?

**Comment by bilogic** [comment]
@code-asher I can re-install some extensions and they do persist after that, but it would be much better if I did not have to do that. What logs can I provide?

**Comment by code-asher** [comment]
Anything in ~/.local/share/code-server/logs might be helpful 
especially if running in debug or maybe even trace mode.  I have 
not had time to repro this so I might be able to immediately see 
something in the logs although I suspect we will have to do some 
deeper debugging.

**Comment by bilogic** [comment]
@code-asher 

I simply could not find the time to look deeper into this, in the end, i extract the list of extensions and reinstalled them on `4.14.0`. Unless someone wants to pursue this, or if the extensions are going to disappear again in the next upgrade, otherwise I propose we drop this.

Thank you.

**Comment by code-asher** [comment]
Sounds good to me.  If anyone has more information please feel 
free to drop it here and we can re-open.
