### ISSUE TITLE
[Bug]: Running a project that opens a localhost doesn't work as expected when using the proxy

### ISSUE THREAD

**Issue by RuiRioPina** [coder/code-server#6116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu 22.04
- Remote OS: Debian
- Remote Architecture: amd64
- `code-server --version`: 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3 with Code 1.76.1

### Steps to Reproduce

1. open code-server
2. have a repository with React / Angular / VueJS, among others
3. open terminal
4. run `npm install`
5. Run start command (it depends. in my case: `npm run dev` for a NextJS app)
6. open the link that appears on the bottom right of the screen 
![image](https://user-images.githubusercontent.com/75616461/228568147-d836c47e-e61d-4fbb-856c-c60d9bac3de7.png)
See error.

### Expected

When I go to http://localhost:3000 it works as expected, however https://localhost:3600/proxy/3000/ doesn't.

https://localhost:3600/proxy/3000/ should display this:
![image](https://user-images.githubusercontent.com/75616461/228568442-571ef3d6-9a0f-4aba-a898-c780fb727e1c.png)

### Actual

It doesn't load the endpoints with the files that come from port 3600 (custom port running codeserver).

![image](https://user-images.githubusercontent.com/75616461/228573496-4a1a74c6-825e-4b8d-9882-6374e785d0d6.png)

### Logs

[IPC Library: Pty Host] TRACE IPty#onData 
added 351 packages, and audited 352 packages in 22s

[IPC Library: Pty Host] TRACE IPty#onData 
116 packages are looking for funding
  run `npm fund` for details

[IPC Library: Pty Host] TRACE IPty#onData 
found 0 vulnerabilities

[IPC Library: Pty Host] TRACE IPty#onData npm
[IPC Library: Pty Host] TRACE IPty#onData  notice 
npm notice New major version of npm available! 8.1.0 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice 

[14:32:32] [File Watcher (parcel)] [ADDED] /work/exercise/node_modules/.package-lock.json
[14:32:32] [File Watcher (parcel)] [CHANGED] /work/exercise/package-lock.json
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#onData root@3006dd54d029:/work/exercise# n
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandFinished 0 15 npm install {
  promptStartMarker: {
    line: 2,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 7,
    _onDispose: '[Circular]'
  },
  commandStartMarker: {
    line: 2,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 8,
    _onDispose: '[Circular]'
  },
  commandStartX: 34,
  commandExecutedMarker: {
    line: 3,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 9,
    _onDispose: '[Circular]'
  },
  commandExecutedX: 0,
  command: 'npm install',
  commandFinishedMarker: {
    line: 15,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 10,
    _onDispose: '[Circular]'
  }
}
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#onCommandFinished {
  command: 'npm install',
  marker: {
    line: 2,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 8,
    _onDispose: '[Circular]'
  },
  endMarker: {
    line: 15,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 10,
    _onDispose: '[Circular]'
  },
  executedMarker: {
    line: 3,
    isDisposed: false,
    _disposables: [ [Object], {}, {}, {}, {} ],
    _id: 9,
    _onDispose: '[Circular]'
  },
  timestamp: 1680100352758,
  cwd: '/work/exercise',
  exitCode: 0
}
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handlePromptStart 0 15
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandStart 34 15
[14:32:32] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/node_modules/.package-lock.json
[14:32:32] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/package-lock.json
2023-03-29 14:32:33,000 INFO  [aca.min.cod.loc.com.CommandExecutorService] (executor-thread-0) Executing command: [/bin/bash, -c, cd /work/exercise && git add .]
[14:32:33] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:33] [File Watcher (node.js)] [raw] ["change"] index.lock
2023-03-29 14:32:33,010 INFO  [aca.min.cod.loc.com.CommandExecutorService] (executor-thread-0) Executing command: Process[pid=2135, exitValue=0]
[14:32:33] [File Watcher (node.js)] [ADDED] /work/exercise/.git/index.lock
2023-03-29 14:32:33,011 INFO  [aca.min.cod.loc.com.CommandExecutorService] (executor-thread-0) Executing command: [/bin/bash, -c, cd /work/exercise && git status]
[14:32:33] [File Watcher (node.js)]  >> ignored (not included) /work/exercise/.git/index.lock
[14:32:33] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:33] [File Watcher (node.js)] [raw] ["rename"] index
[14:32:33] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:33] [File Watcher (node.js)] [raw] ["rename"] index.lock

[14:32:33] [File Watcher (parcel)] [ADDED] /work/exercise/.git/index
[14:32:33] [File Watcher (node.js)] [CHANGED] /work/exercise/.git/index
[14:32:33] [File Watcher (node.js)]  >> ignored (not included) /work/exercise/.git/index
[14:32:33] [File Watcher (node.js)] [DELETED] /work/exercise/.git/index.lock
[14:32:33] [File Watcher (node.js)]  >> ignored (not included) /work/exercise/.git/index.lock
[14:32:33] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.git/index
[IPC Library: Pty Host] TRACE ptyService#setLayoutInfo [
  {
    isActive: true,
    activePersistentProcessId: 1,
    terminals: [ [Object] ]
  }
]
[IPC Library: Pty Host] TRACE IPty#write o
[IPC Library: Pty Host] TRACE IPty#onData o
[IPC Library: Pty Host] TRACE IPty#write n
[IPC Library: Pty Host] TRACE IPty#onData n
[IPC Library: Pty Host] TRACE IPty#write 
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#write 
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#write p
[IPC Library: Pty Host] TRACE IPty#onData p
[IPC Library: Pty Host] TRACE IPty#write o
[IPC Library: Pty Host] TRACE IPty#onData o
[IPC Library: Pty Host] TRACE IPty#write 
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#write m
[IPC Library: Pty Host] TRACE IPty#onData m
[IPC Library: Pty Host] TRACE IPty#write  
[IPC Library: Pty Host] TRACE IPty#onData  
[IPC Library: Pty Host] TRACE IPty#write r
[IPC Library: Pty Host] TRACE IPty#onData r
[IPC Library: Pty Host] TRACE IPty#write u
[IPC Library: Pty Host] TRACE IPty#onData u
[IPC Library: Pty Host] TRACE IPty#write n
[IPC Library: Pty Host] TRACE IPty#onData n
[IPC Library: Pty Host] TRACE IPty#write  
[IPC Library: Pty Host] TRACE IPty#onData  
[IPC Library: Pty Host] TRACE IPty#write d
[IPC Library: Pty Host] TRACE IPty#onData d
[IPC Library: Pty Host] TRACE IPty#write e
[IPC Library: Pty Host] TRACE IPty#onData e
[IPC Library: Pty Host] TRACE IPty#write v
[IPC Library: Pty Host] TRACE IPty#onData v
[IPC Library: Pty Host] TRACE IPty#write 
[IPC Library: Pty Host] TRACE IPty#onData 

[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] TRACE IPty#onData 
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandExecuted 0 16
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#setCommandLine npm run dev
[IPC Library: Pty Host] TRACE IPty#onData 
> adventure-helper@0.1.0 dev
> next dev

[IPC Library: Pty Host] TRACE IPty#onData ready - started server on 0.0.0.0:3000, url: http://localhost:3000

[14:32:42] [File Watcher (parcel)] [ADDED] /work/exercise/next-env.d.ts
[14:32:42] [File Watcher (parcel)] [ADDED] /work/exercise/.next
[14:32:42] [File Watcher (parcel)] [ADDED] /work/exercise/.next/package.json
[14:32:42] [File Watcher (parcel)] [CHANGED] /work/exercise/next-env.d.ts
[14:32:42] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/next-env.d.ts
[14:32:42] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next
[14:32:42] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/package.json
[14:32:42] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache
[14:32:42] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache
2023-03-29 14:32:43,000 INFO  [aca.min.cod.loc.com.CommandExecutorService] (executor-thread-0) Executing command: [/bin/bash, -c, cd /work/exercise && git add .]
[14:32:43] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:43] [File Watcher (node.js)] [raw] ["rename"] index.lock

[14:32:43] [File Watcher (node.js)] [DELETED] /work/exercise/.git/index.lock
[14:32:43] [File Watcher (node.js)]  >> ignored (not included) /work/exercise/.git/index.lock
[14:32:43] [File Watcher (parcel)] [ADDED] /work/exercise/.next/trace
[14:32:43] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/trace
[14:32:43] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/trace
[14:32:43] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/trace
[IPC Library: Pty Host] TRACE IPty#onData 

[IPC Library: Pty Host] TRACE IPty#onData warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration

[14:32:45] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/trace
[14:32:45] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/trace
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/build-manifest.json
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/react-loadable-manifest.json
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/font-loader-manifest.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/font-loader-manifest.json
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/middleware-build-manifest.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/middleware-react-loadable-manifest.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/amp.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/main.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/pages
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/pages/_app.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/pages/_error.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/polyfills.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/react-refresh.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/webpack.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/development
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/development/_buildManifest.js
[14:32:46] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/development/_ssgManifest.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/build-manifest.json
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/react-loadable-manifest.json
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/font-loader-manifest.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/font-loader-manifest.json
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/middleware-build-manifest.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/middleware-react-loadable-manifest.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/amp.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/main.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/pages
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/pages/_app.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/pages/_error.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/polyfills.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/react-refresh.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/webpack.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/development
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/development/_buildManifest.js
[14:32:46] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/development/_ssgManifest.js
[2023-03-29T14:32:46.711Z] debug 2 active connections
Trace: [2023-03-29T14:32:46.711Z] trace heartbeat
    at doLog (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:57:28)
    at ServerFormatter.doWrite (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:200:20)
    at ServerFormatter.write (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:119:14)
    at Logger.handle (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:339:25)
    at Logger.trace (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:268:14)
    at Heart.<anonymous> (/usr/lib/code-server/out/node/heart.js:41:29)
    at Generator.next (<anonymous>)
    at /usr/lib/code-server/out/node/heart.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/code-server/out/node/heart.js:4:12)
    at Heart.beat (/usr/lib/code-server/out/node/heart.js:37:16)
    at /usr/lib/code-server/out/node/heart.js:76:17
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/heart.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[IPC Library: Pty Host] TRACE IPty#onData event - compiled client and server successfully in 4.5s (165 modules)

[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/middleware-manifest.json
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages-manifest.json
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages/_app.js
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages/_document.js
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages/_error.js
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/webpack-runtime.js
[14:32:47] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/trace
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/middleware-manifest.json
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages-manifest.json
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages/_app.js
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages/_document.js
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages/_error.js
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/webpack-runtime.js
[14:32:47] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/trace
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/config.json.4197236165
[IPC Library: Pty Host] TRACE IPty#onData Attention: Next.js now collects completely anonymous telemetry regarding usage.

[IPC Library: Pty Host] TRACE IPty#onData This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/config.json
[14:32:47] [File Watcher (parcel)] [DELETED] /work/exercise/.next/cache/config.json.4197236165
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/config.json
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/config.json
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/config.json
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack
[14:32:47] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack
[14:32:47] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development
[14:32:48] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/0.pack
[14:32:48] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/index.pack
[14:32:48] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/0.pack
[14:32:48] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/index.pack
[14:32:48] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/server-development
[14:32:48] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/server-development/0.pack
[14:32:48] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/server-development/index.pack
[14:32:48] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/server-development
[14:32:48] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/server-development/0.pack
[14:32:48] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/server-development/index.pack
[IPC Library: Pty Host] TRACE ptyService#setLayoutInfo [
  {
    isActive: true,
    activePersistentProcessId: 1,
    terminals: [ [Object] ]
  }
]
[IPC Library: Pty Host] TRACE IPty#onData wait  - compiling / (client and server)...

[14:32:53] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:53] [File Watcher (node.js)] [raw] ["rename"] index.lock
[14:32:53] [File Watcher (parcel)] [DELETED] /work/exercise/.git/index.lock
[14:32:53] [File Watcher (node.js)] [DELETED] /work/exercise/.git/index.lock
[14:32:53] [File Watcher (node.js)]  >> ignored (not included) /work/exercise/.git/index.lock
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/build-manifest.json
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/react-loadable-manifest.json
[14:32:54] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/webpack
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/build-manifest.json
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/react-loadable-manifest.json
[14:32:54] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/webpack
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/build-manifest.json
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/react-loadable-manifest.json
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/server/font-loader-manifest.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/server/font-loader-manifest.json
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/server/middleware-build-manifest.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/server/middleware-react-loadable-manifest.js
[14:32:54] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/chunks/pages/index.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/static/chunks/webpack.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/static/development/_buildManifest.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/static/development/_ssgManifest.js
[14:32:54] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/webpack/d7fd5e482aa87249.webpack.hot-update.json
[14:32:54] [File Watcher (parcel)] [ADDED] /work/exercise/.next/static/webpack/webpack.d7fd5e482aa87249.hot-update.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/build-manifest.json
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/react-loadable-manifest.json
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/server/font-loader-manifest.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/server/font-loader-manifest.json
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/server/middleware-build-manifest.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/server/middleware-react-loadable-manifest.js
[14:32:54] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/chunks/pages/index.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/static/chunks/webpack.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/static/development/_buildManifest.js
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/static/development/_ssgManifest.js
[14:32:54] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/webpack/d7fd5e482aa87249.webpack.hot-update.json
[14:32:54] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/static/webpack/webpack.d7fd5e482aa87249.hot-update.js
[14:32:54] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/trace
[14:32:54] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/trace
[IPC Library: Pty Host] TRACE IPty#onData event - compiled client and server successfully in 2.1s (228 modules)

[14:32:55] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/server/pages-manifest.json
[14:32:55] [File Watcher (parcel)] [ADDED] /work/exercise/.next/server/pages/index.js
[14:32:55] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/trace
[14:32:55] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/server/pages-manifest.json
[14:32:55] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/server/pages/index.js
[14:32:55] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/trace
[14:32:55] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:55] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:55] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:55] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:56] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/0.pack
[14:32:56] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/1.pack
[14:32:56] [File Watcher (parcel)] [DELETED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:56] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/cache/webpack/client-development/index.pack
[14:32:56] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/client-development/index.pack.old
[14:32:56] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/server-development/1.pack
[14:32:56] [File Watcher (parcel)] [CHANGED] /work/exercise/.next/cache/webpack/server-development/index.pack
[14:32:56] [File Watcher (parcel)] [ADDED] /work/exercise/.next/cache/webpack/server-development/index.pack.old
[14:32:56] [File Watcher (parcel)]  >> normalized [DELETED] /work/exercise/.next/cache/webpack/client-development/1.pack_
[14:32:56] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/0.pack
[14:32:56] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/1.pack
[14:32:56] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/cache/webpack/client-development/index.pack
[14:32:56] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/client-development/index.pack.old
[14:32:56] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/server-development/1.pack
[14:32:56] [File Watcher (parcel)]  >> normalized [CHANGED] /work/exercise/.next/cache/webpack/server-development/index.pack
[14:32:56] [File Watcher (parcel)]  >> normalized [ADDED] /work/exercise/.next/cache/webpack/server-development/index.pack.old

### Screenshot/Video

![image](https://user-images.githubusercontent.com/75616461/228567831-0f31aaad-7117-4082-89bc-6e09028a412d.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

https://localhost:3000 doesn't work as expected. It gives the same error as https://localhost:3600/proxy/3000/

**Comment by code-asher** [comment]
It looks like issue is that the application is making absolute 
requests against the root instead of using relative requests.

To fix you probably need to tell the application about the 
`/proxy/3000` base path so it makes requests to the right path. 
You might also have to use `/absproxy` instead of `/proxy` (the 
latter rewrites the request to remove the base path while the 
former does not).

These might help:
https://github.com/coder/code-server/discussions/5837
https://github.com/coder/code-server/issues/5831#issuecomment-1337708109

Alternatively you could use the subdomain proxy which works a lot 
better for applications that get confused by being proxied at a 
subpath.  For example:

```
VSCODE_PROXY_URI=http://{{port}}.localhost:3000 code-server --proxy-domain *.localhost
```

Setting `VSCODE_PROXY_URI` is only something that needs to be done 
for the current version or lower, in the next version it will be 
set automatically and you will only need `--proxy-domain`.

**Comment by RuiRioPina** [comment]
Worked in the first try. I had already read the [docs](https://coder.com/docs/code-server/latest/guide#proxying-to-create-a-react-app
) on it but was a bit confused on where I should have put this config. Thank you for clarifying :smile:
