### ISSUE TITLE
[Bug]: Source Control Panel is blank

### ISSUE THREAD

**Issue by zctmdc** [coder/code-server#6120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge 版本 109.0.1518.95 (正式版本) (64 位)
- Local OS: Windows 7
- Remote OS: docker (linuxserver/code-server:latest - Ubuntu 20.04.3 LTS) On OpenWRT x86_64 (iStoreOS 21.02.3 2023033111 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111)
- Remote Architecture: x86_64
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

```shell
abc@ED-iStoreOS:/mnt/workspace/docker$ cat /proc/version 
Linux version 5.4.188 (build@buildserver) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 2022091511)) #0 SMP Thu Mar 30 06:40:36 2023
abc@ED-iStoreOS:/mnt/workspace/docker$ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

### Steps to Reproduce

1. open code-server
2. install extension
3. git clone <project>
4. edit files
5. open `Source Control`
6. it's blank

### Expected

Show modified files

### Actual

Source Control is blank, edge console show some erro log,

### Logs

```JavaScript
 ERR Invalid comparison: Error: Invalid comparison
    at _e.compare (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:2349:15111)
    at Object.compare (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:87569)
    at Object.compare (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:78387)
    at Array.sort (<anonymous>)
    at M.preserveCollapseState (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:79326)
    at M.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:78595)
    at l._setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:84914)
    at l.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:84032)
    at u.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:88425)
    at X.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:192:8634)
```
```javaScript
 ERR Unknown compressed tree node: Error: Unknown compressed tree node
    at l.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:84142)
    at u.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:70:88425)
    at X.setChildren (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:192:8634)
    at Fe.refresh (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:2349:27372)
    at Fe._onDidSpliceGroup (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:2349:25889)
    at https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:2349:25406
    at l.fire (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:69:1712)
    at v.splice (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:1526:33597)
    at d.$spliceGroupResourceStates (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:1526:36410)
    at n.$spliceResourceStates (https://code.ed.zctmdc.cn/static/out/vs/workbench/workbench.web.api.js:1526:38654)
```

### Screenshot/Video

![image](https://user-images.githubusercontent.com/24244480/229277279-1eac8bc2-d98c-4d75-812e-0da08e8df178.png)

![image](https://user-images.githubusercontent.com/24244480/229277932-60d46d05-efd3-4783-8252-0a79f8d21af4.png)

![image](https://user-images.githubusercontent.com/24244480/229278144-3ffdc387-9221-4814-a1ea-3618e6aed86b.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

It is look like #1210

**Comment by zctmdc** [comment]
just click `SOURCE CONTROL` `···` `Commit` `Undo Last Commit`, it will be fixed. 
只要点击 `源代码管理` `右边的三个点` `提交` `撤销上次提交`, 它就自己好了。
