### ISSUE TITLE
[Bug]: Can't login and sync setting.

### ISSUE THREAD

**Issue by w0330t** [coder/code-server#6293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 11
- Remote OS: Archlinux
- Remote Architecture:  amd64
- `code-server --version`:  4.14.1

### Steps to Reproduce

1. Click "Accounts" Button
2. Click menu item "Turn on Cloud Change..."
3. Noting happend

![image](https://github.com/coder/code-server/assets/4970238/2a92d9a1-35d5-4b0f-8d50-85b961feddf5)

### Expected

Open new window login Microsoft or Github account

### Actual

Nothing happened

### Logs

```
[w0330t@ArchVM ~]$ code-server --verbose
[2023-06-28T12:22:10.867Z] debug parent:8648 spawned child process 8669
[2023-06-28T12:22:11.192Z] debug child:8669 initiating handshake
[2023-06-28T12:22:11.194Z] debug parent:8648 got message {"message":{"type":"handshake"}}
[2023-06-28T12:22:11.196Z] debug child:8669 got message {"message":{"type":"handshake","args":{"bind-addr":"0.0.0.0:8080","auth":"password","password":"<redacted>","config":"/home/w0330t/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/home/w0330t/.local/share/code-server","extensions-dir":"/home/w0330t/.local/share/code-server/extensions","session-socket":"/home/w0330t/.local/share/code-server/code-server-ipc.sock","log":"trace","host":"0.0.0.0","port":8080,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
[2023-06-28T12:22:11.196Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-06-28T12:22:11.196Z] info  Using user-data-dir ~/.local/share/code-server
Trace: [2023-06-28T12:22:11.196Z] trace Using extensions-dir ~/.local/share/code-server/extensions
    at doLog (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:57:28)
    at ServerFormatter.doWrite (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:200:20)
    at ServerFormatter.write (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:119:14)
    at Logger.handle (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:339:25)
    at Logger.trace (/usr/lib/code-server/node_modules/@coder/logger/out/logger.js:268:14)
    at /usr/lib/code-server/out/node/main.js:119:21
    at Generator.next (<anonymous>)
    at /usr/lib/code-server/out/node/main.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/code-server/out/node/main.js:27:12)
[2023-06-28T12:22:11.200Z] error listen EADDRINUSE: address already in use 0.0.0.0:8080
[2023-06-28T12:22:11.200Z] debug child:8669 disposing {}
[2023-06-28T12:22:11.204Z] debug parent:8648 inner process 8669 exited unexpectedly
[2023-06-28T12:22:11.205Z] debug parent:8648 disposing {}
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I believe settings sync is designed to only work with VS Code-branded products, not OSS builds like code-server, which unfortunately means there might be nothing we can do.

Still, we should investigate and if there is nothing we can do we should at least patch the button out so it does not appear.

**Comment by Aetherinox** [comment]
I guess this explains why I clicked the Cloud button about 20 times with no result.

It's sad about Setting Sync, that used to be an amazing plugin. I preferred it over VSCode's built in sync functionality.

Hopefully something goes done to address this. Even a self-hosted option would be better than nothing, or re-adding the ability to sync to a gist.

**Comment by code-asher** [comment]
Closing for now since this is by Microsoft's design.
