### ISSUE TITLE
[Bug]: code-server cannot install ms-vscode.cpptools and ms-vscode.cpptools-extension-pack directly from marketplace

### ISSUE THREAD

**Issue by zengqingfu1442** [coder/code-server#6430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: google chrome 116.0.5845.180 
- Local OS: windows 10
- Remote OS: ubuntu 20.04
- Remote Architecture: x86_64
- `code-server --version`: 1.80.2   2ccd690cbff1569e4a83d7c43d45101f817401dc   x64

### Steps to Reproduce

1.  `code-server --install-extension ms-vscode.cpptools` failed
2.  download https://github.com/microsoft/vscode-cpptools/releases/download/v1.17.5/cpptools-linux.vsix, and then i can install it locally
3.  `code-server --install-extension ms-vscode.cpptools-extension-pack` failed
4. Manually download from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack, and then locally install it but still failed. The error message is shown below,
'''
code-server --install-extension ms-vscode.cpptools-extension-pack-1.3.0.vsix 
Installing extensions on 172.16.31.235:32769...
Error: Corrupt ZIP: end of central directory record signature not found
    at h (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:152:70451)
    at /usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:152:71806
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:37:7
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:187:5
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:631:5
    at /usr/lib/code-server/lib/vscode/node_modules/fd-slicer/index.js:32:7
    at callback (/usr/lib/code-server/lib/vscode/node_modules/graceful-fs/polyfills.js:132:21)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
'''

### Expected

i expect use this command `code-server --install-extension ms-vscode.cpptools --install-extension ms-vscode.cpptools-extension-pack` to directly install the two extensions from marketplace. At least, i can manually download them and install them two successfully locally.

### Actual

The two extensions cannot be found in the marketplace, and "ms-vscode.cpptools-extension-pack" cannot be installed even at local.

### Logs

code-server --install-extension ms-vscode.cpptools-extension-pack-1.3.0.vsix 
Installing extensions on 172.16.31.235:32769...
Error: Corrupt ZIP: end of central directory record signature not found
    at h (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:152:70451)
    at /usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:152:71806
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:37:7
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:187:5
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:631:5
    at /usr/lib/code-server/lib/vscode/node_modules/fd-slicer/index.js:32:7
    at callback (/usr/lib/code-server/lib/vscode/node_modules/graceful-fs/polyfills.js:132:21)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

ms-vscode.cpptools and ms-vscode.cpptools-extension-pack cannot be installed in code-server.

**Comment by code-asher** [comment]
Can you reproduce this with other extensions?  Unfortunately the 
license of those extensions does not allow their use with 
code-server so I am not able to test.

Are you able to extract them yourself with `unzip` to ensure they 
are not corrupted?  If so, a workaround could be to extract them 
to the extensions directory.

**Comment by code-asher** [comment]
Closing for lack of activity, but feel free to post and we can reopen.
