### ISSUE TITLE
[Bug]: argon2.node: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Dual-0** [coder/code-server#6446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

After a update to v4.17.0 on my Ubuntu ARM64 instance I got this failure.
I used the `.deb` file.
```
user@ubuntu:~$ code-server
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/lib/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```
v4.16.1 is still working

regards
Dual-O

### Steps to Reproduce

1. update to v4.17.0
2. execute code-server via command line

### Expected

working like v4.16.1

### Actual

error via command line output

### Logs

node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/lib/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.15.0

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by eugeneewe** [comment]
Same here facing the error after Watchtower update the container.
`Node.js v18.15.0
starting with no password
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /app/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}`

**Comment by fettesb** [comment]
Same for me after Watchtower update the Container

starting with no password
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /app/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Node.js v18.15.0

**Comment by eltorio** [comment]
same here on Ampere Altra A1 (arm64)
```
Error: /usr/lib/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/lib/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by eltorio** [comment]
my workaround: (in */usr/lib/code-server*)
```sh
cd /usr/lib/code-server \
&& rm -rf node_modules/argon2 \
&& npm install -g node-gyp \
&& npm install argon2 argon2-cli \
&& echo -n "password" | npx argon2-cli -d -e
```

**Comment by fate8383** [comment]
I have the same issue

**Comment by wxianxin** [comment]
Same issue on raspberry pi 4.

**Comment by eltorio** [comment]
@wxianxin this issue is present on all arm64 because the /usr/lib/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node is not a correct aarch64 binary, you must recompile it yourself 

> `code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node` is not a valid aarch64 ELF binary so my workaround is to force to recompile it with node-gyp pre-installed… **my workaround: (in _/usr/lib/code-server_)**
> 
> ```shell
> cd /usr/lib/code-server \
> && rm -rf node_modules/argon2 \
> && npm install -g node-gyp \
> && npm install argon2 argon2-cli \
> && echo -n "password" | npx argon2-cli -d -e
> ```

**Comment by kvnkmth** [comment]
@eltorio  thanks it works!

**Comment by wxianxin** [comment]
> @wxianxin this issue is present on all arm64 because the /usr/lib/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node is not a correct aarch64 binary, you must recompile it yourself
> 
> > `code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node` is not a valid aarch64 ELF binary so my workaround is to force to recompile it with node-gyp pre-installed… **my workaround: (in _/usr/lib/code-server_)**
> > ```shell
> > cd /usr/lib/code-server \
> > && rm -rf node_modules/argon2 \
> > && npm install -g node-gyp \
> > && npm install argon2 argon2-cli \
> > && echo -n "password" | npx argon2-cli -d -e
> > ```

Thanks! I am on a k8s cluster, probably will wait for the image maintainer to fix the issue. Appreciate the insight!

**Comment by AnggiWaSa** [comment]
> `code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node` is not a valid aarch64 ELF binary so my workaround is to force to recompile it with node-gyp pre-installed… **my workaround: (in _/usr/lib/code-server_)**
> 
> ```shell
> cd /usr/lib/code-server \
> && rm -rf node_modules/argon2 \
> && npm install -g node-gyp \
> && npm install argon2 argon2-cli \
> && echo -n "password" | npx argon2-cli -d -e
> ```

Thank you @eltorio , this helped me in resolving the issue

**Comment by Niko-La** [comment]
getting this error on mac m1 running code-server docker-compose

**Comment by code-asher** [comment]
Thank you for the reports.  I think I have a fix for this.  Once CI completes I will put out an RC and if there is anyone who could run it in an arm64 environment to confirm I would be most grateful!
