### ISSUE TITLE
[Bug]: code-server is installing `web` target instead of `linux-x64` target of the extension

### ISSUE THREAD

**Issue by jakubmisek** [coder/code-server#6489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge 117.0.2045.60
- Local OS: Windows 11
- Remote OS: WSL 2
- Remote Architecture: linux-x64
- `code-server --version`: 4.17.1 2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa with Code 1.82.2

### Steps to Reproduce

1. switch to the Extensions panel
2. search for `PHP` extension
3. click install

![image](https://github.com/coder/code-server/assets/842150/e830b7e8-8e7b-4fd2-a637-c0b82d338c6e)

### Expected

The `linux-x64` target of the extension gets installed on the server.

### Actual

It tries to install the `web` target of the extension, which does not work, and is not intended for use on the `code-server`.

![image](https://github.com/coder/code-server/assets/842150/421f5741-b9e4-419c-8487-1dcaff11a171)

### Logs

```
ERR Failed to install extension. devsense.phptools-vscode
2log.ts:441   ERR IncompatibleTargetPlatform: The 'devsense.phptools-vscode' extension is not available in code-server for Web.
    at s.J (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:30909)
    at async http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21801
    at async Promise.allSettled (index 0)
    at async s.installGalleryExtensions (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21725)
    at async s.installFromGallery (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21314)
    at async Promise.all (index 0)
    at async Object.J [as settled] (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:77:22594)
    at async http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:2659:23140
log.ts:441   ERR The 'devsense.phptools-vscode' extension is not available in code-server for Web.: IncompatibleTargetPlatform: The 'devsense.phptools-vscode' extension is not available in code-server for Web.
    at s.J (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:30909)
    at async http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21801
    at async Promise.allSettled (index 0)
    at async s.installGalleryExtensions (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21725)
    at async s.installFromGallery (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:760:21314)
    at async Promise.all (index 0)
    at async Object.J [as settled] (http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:77:22594)
    at async http://127.0.0.1:8080/stable-2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa/static/out/vs/workbench/workbench.web.main.js:2659:23140
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

Installing `linux-x64` target manually (downloading the VSIX file, and installing it using `Install from VSIX` command works as expected.

**Comment by python-and-fiction** [comment]
I try to install this extension in my platforms. I think that you should expect web target installed in code-server.

Clicked install button in vscode.dev:
![vscode dev](https://github.com/coder/code-server/assets/16256910/81cbf9d1-1893-4f79-a91d-3f8d12944e38)

Clicked install button in vscode server selfhosted on Debian machine:
![vscode selfhost web](https://github.com/coder/code-server/assets/16256910/284bb487-ee12-47ac-8320-8ed67bea01d3)

Mannually install web version from vsix in vscode server selfhosted on Deabin machine:
![vscode selfhost web manually](https://github.com/coder/code-server/assets/16256910/0159f493-c4bd-4225-8b92-bc37fa8ef960)

Mannually install web version from vsix in code-server  on Debian machine:
![codeserver web](https://github.com/coder/code-server/assets/16256910/e49b5721-25d8-4874-8df8-884b79554cb7)

Mannually install linux-x64 version from vsix in code-server  on Debian machine:
![codeserver native](https://github.com/coder/code-server/assets/16256910/b6b3e071-9358-495d-adc3-8e68e2d07127)

Maybe code-server should work as vscode server selfhosted,but vscode.dev shows that web version is installed

**Comment by jakubmisek** [comment]
@python-and-fiction thank you for your steps.

I'm the extension author, and

- `web` target properly works on vscode.dev (that's why we created the special and limited web version of the extension) - for running completely in the browser.
- `linux-x64` target is however intended for running on server/Linux architectures. `code-server` does not host extensions in the browser, it hosts them on the server side.

Moreover, the `web` version does not install (see the error message in the issue), so either `linux-x64` target should be installed (because the extension host does not run in the browser), or the `web` target should at least work.

If there is no fix, or if there is no "metadata" we can put into `package.json`, the only workaround I can see is - to get rid of the `web` target?

**Comment by code-asher** [comment]
code-server is more similar to Codespaces (which has a server end) than vscode.dev (vscode.dev has no server end I think right?), and in Codespaces I see the same behavior (installed as a browser extension).

Seems like this is related: https://github.com/microsoft/vscode/issues/189280.  Possibly setting `extensionKind` to `workspace` is a fix?  Seems Jupyter fixed it that way: https://github.com/microsoft/vscode-jupyter/pull/14273/files

**Comment by jakubmisek** [comment]
@code-asher thank you very much, I thought `"workspace"` was the default.

We'll try that. Maybe the `web`'s `package.json` will need `["ui"]` ``extensionKind`.

**Comment by code-asher** [comment]
Yeah apparently (according to the last comment) the problem comes from them fetching any package.json and assuming it is the same across each platform.  It sounds then like the web's package.json needs `["workspace"]` but I am a little hazy on if I am understanding correctly.

Jupyter does seem to have a separate web .vsix: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2023.10.1002921100/vspackage?targetPlatform=web

And if we check the package.json in the downloaded vsix it has `["workspace"]` so seems promising.

**Comment by jakubmisek** [comment]
thank you @code-asher - we'll release `web` and other VSIXes with the altered `extensionKind` and we'll see.

**Comment by jakubmisek** [comment]
It works! Annotating the `web` extension with `"extensionKind": ["workspace"]` does the trick.

Thank you @code-asher and everyone commenting me on the issue.

Also, the `web` extension still works in the browser on vscode.dev.
