### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by firasm** [coder/code-server#6630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari/Firefox/Chrome etc...
- Local OS: macOS
- Remote OS: Linux
- Remote Architecture: amd64
- `code-server --version`: 4.20.0

### Steps to Reproduce

1. Run code-server
2.  Install the "Test Runner for Java" extension (+ other associated extensions)
3. Use [this](https://github.com/firasm/reprex_java_tests) project as a barebones demo
4. Click on the Beaker on the left sidebar to try and run the Java Tests
5. The Java tests will fail the first time with an error
6. Running it again (doing nothing else) will run fine

### Expected

No error the first time! 

### Actual

Error the first time, runs fine the next time

### Logs

Here's the error:

```
Class not found model.ProjectInNeedTest
java.lang.ClassNotFoundException: model.ProjectInNeedTest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
BuiltinClassLoader.java:581
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
ClassLoader.java:527
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:766)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:490)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [x] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

Hello,

My colleagues and I are trying to use the "Test Runner for Java" extension in a workspace using VS Code in the browser (specifically the [code-server](https://github.com/coder/code-server) project). 

We are trying to troubleshoot a really strange issue that only shows up in the cloud, and not when trying to run things locally.

[Here is a very very simple Java project](https://github.com/firasm/reprex_java_tests) that when it's run in the browser, gives a `Class not found model.SampleTest` error.

<img width="1146" alt="Screenshot 2024-01-18 at 8 56 46 PM" src="https://github.com/microsoft/vscode-java-test/assets/2507459/68e11801-9c28-48e1-ae46-2aeb3f1833b8">

However, when you do nothing else except just run the test one more time, it works just fine:

<img width="1272" alt="Screenshot 2024-01-18 at 8 57 03 PM" src="https://github.com/microsoft/vscode-java-test/assets/2507459/ae65d0eb-7663-48ac-b929-f3a717337908">

This happens for **every** project that's run in the cloud this way, so we are nearly 100% sure that it's got something to do with being execute remotely. The stack trace seems useful, but it's not something that gives me any insight so I thought I'd post here to ask for help in troubleshooting!

I also posted this in the [vscode-java-test repo](https://github.com/microsoft/vscode-java-test/issues/1650) in case this was an issue with the extension.

Thanks for any advice you have to try and troubleshoot this.

**Comment by firasm** [comment]
P.S. I was *not* able to reproduce this bug in GitHub Codespaces. There the tests ran fine the first time.

**Comment by code-asher** [comment]
Hmm, maybe not, the extension seems to work for me (v0.40.1) following the reproduction steps.  I only installed `vscjava.vscode-java-test`, no other Java-related extensions.  My Java version in case that indicates something:

```
$ java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

**Comment by code-asher** [comment]
Closing for inactivity, but let me know if the issue persists and we can continue trying to debug.
