### ISSUE TITLE
[Bug]: run command `yarn build:vscode`。Unexpected error occurred

### ISSUE THREAD

**Issue by kevinKaikai** [coder/code-server#6684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

-- Remote OS:Ubuntu

### Steps to Reproduce

1.Successfully run the following command
![e1133a4cfbcac93566ebc221b05915c](https://github.com/coder/code-server/assets/37619768/8705816a-9254-4b4e-b358-dd491e11b927)
2. run `yarn build` command successfully。
3. run `yarn build:vscode`

### Expected

build successfully

### Actual

[14:27:32] AbortError: The user aborted a request.
    at abort (/home/intewell/CODE_SERVER/code-server/lib/vscode/build/node_modules/node-fetch/lib/index.js:1448:16)
    at EventTarget.abortAndFinalize (/home/intewell/CODE_SERVER/code-server/lib/vscode/build/node_modules/node-fetch/lib/index.js:1463:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
    at EventTarget.dispatchEvent (node:internal/event_target:721:26)
    at abortSignal (node:internal/abort_controller:369:10)
    at AbortController.abort (node:internal/abort_controller:403:5)
    at Timeout.&lt;anonymous&gt; (/home/intewell/CODE_SERVER/code-server/lib/vscode/build/lib/fetch.js:44:53)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![7c37bc14e0cc16abbede3029d35cc4c](https://github.com/coder/code-server/assets/37619768/bd5c4bd6-a874-4d20-ab74-ecb101beefb7)

### Screenshot/Video

![7c37bc14e0cc16abbede3029d35cc4c](https://github.com/coder/code-server/assets/37619768/d2112419-8d56-426c-8859-e57a61ab43c6)

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Seems like maybe it timed out trying to download those extensions from GitHub.  Are you able to `curl` or `wget` `https://github.com/microsoft/vscode-js-profile-visualizer/releases/download/v1.0.8/ms-vscode.vscode-js-profile-table.1.0.8.vsix` from that machine?

**Comment by code-asher** [comment]
Closing as stale, but feel free to comment if you come back to this.
