### ISSUE TITLE
Cannot sign in to github

### ISSUE THREAD

**Issue by acester822** [coder/code-server#6903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: CHrome
- Local OS: Arch Linux
- Remote OS: Any
- Remote Architecture: amd64
- `code-server --version`: 4.23.1-ls206

### Steps to Reproduce

1. Try to sign into github from any extension
2. 
3.

### Expected

Sign in flow should complete properly

### Actual

It never pops up providing me with a token, instead I get this, You have not yet finished authorizing this extension to use GitHub. Would you like to try a different way? (personal access token). When I click that it forwards me to github to make a token, I make it, and when I enter it in codeserver it throws an error, Sign in failed: Error: No auth flow succeeded.

### Logs

2024-07-17 09:17:55.090 [error] Error: No auth flow succeeded.
	at a.GitHubServer.login (/usr/lib/code-server/lib/vscode/extensions/github-authentication/dist/extension.js:1:228252)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async a.GitHubAuthenticationProvider.createSession (/usr/lib/code-server/lib/vscode/extensions/github-authentication/dist/extension.js:1:223487)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

### Notes

This is on a local linux install. On a remote docker version, the sign in works fine, no issues.

**Comment by acester822** [comment]
I figured it out, was an issue with proxy settings, 

This did NOT work,
Settings:
- http.proxy: https://yourproxy.dev
  - globalValue: https://yourproxy.dev
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: on
  - globalValue: on
- http.systemCertificates: true

This works fine:
Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true
