### ISSUE TITLE
Global search "ctrl+shift+f" breaks randomly

### ISSUE THREAD

**Issue by SidSeed** [coder/code-server#6942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOs
- Remote OS: Ubuntu
- Remote Architecture: x86_64
- `code-server --version`: 4.20.0

### Steps to Reproduce

I am not able to reproduce it, it happens randomly few times a day.

### Expected

Returns the search results

### Actual

Search result are not shown, show an error instead: The file containing the result is not a descendant of the workspace.

### Logs

```shell
2024-07-22 15:43:23.528 [error] vscode-remote://domain.com/user1/workspaceFolder/repository/var/shocks/engine.py?%7B%22path%22%3A%22%2Fuser12FworkspaceFolder%2Frepository%2Fvar%2Fshocks%2Fengine.py%22%7D is not a descendant of vscode-remote://domain.com/user1/workspaceFolder: Error: vscode-remote://domain.com/user1/workspaceFolder/repository/var/shocks/engine.py?%7B%22path%22%3A%22%2Fuser12FworkspaceFolder%2Frepository%2Fvar%2Fshocks%2Fengine.py%22%7D is not a descendant of vscode-remote://domain.com/user1/workspaceFolder
    at _.createAndConfigureFileMatch (https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:16803)
    at https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:13869
    at Array.forEach (<anonymous>)
    at _.addFileMatch (https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:13372)
    at https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:21980
    at S.forEach (https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:20:30604)
    at X.add (https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:21922)
    at https://domain.com/apps/r/dev/0%20IDE%20%28Alpha%29/stable-d0215eca8804d0be5d3551c39404e336032c3141/static/out/vs/workbench/workbench.web.main.js:2576:27294
```

### Screenshot/Video

![search_err](https://github.com/user-attachments/assets/ca5a5ee5-e933-445a-a902-3a0677ccbfe6)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

sometimes deleting the indexeddb helps to fix it for a short period of time.
Killing code-server few times and starting it again fixes it, but again for a short period of time.

**Comment by code-asher** [comment]
Very strange.  We might want to try reproducing in Codespaces so we can report it upstream, I am not sure what code-server could be doing to cause this.

I did briefly experiment but so far have not reproduced.

**Comment by code-asher** [comment]
Closing for now, but let me know if you come back to this.
