### ISSUE TITLE
Error when running on termux proot distro

### ISSUE THREAD

**Issue by glennmalau** [coder/code-server#7043]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: -
- Local OS: Android
- Remote OS: -Android
- Remote Architecture: Arm64
- `code-server --version`: 4.93.1

### Steps to Reproduce

$proot-distro login Ubuntu
$cd code-server/bin
$./code-server

### Expected

node:internal/modules/cjs/loader:1452
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /root/code-server-4.93.1-linux-amd64/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/code-server-4.93.1-linux-amd64/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.19.1

### Actual

Eror

### Logs

node:internal/modules/cjs/loader:1452
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /root/code-server-4.93.1-linux-amd64/node_modules/argon2/lib/binding/napi-v3/argon2.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/code-server-4.93.1-linux-amd64/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.19.1

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by python-and-fiction** [comment]
you should run code-server arm64.

**Comment by code-asher** [comment]
Closing for now since it seems to be an incorrect arch issue, but let us know if that is not the case.
