### ISSUE TITLE
ptyHost crashes resulting in the terminal disconnecting

### ISSUE THREAD

**Issue by phorcys420** [coder/code-server#7123]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: `4.95.3 b0c935a6e0742adde9f7a5f6e5816553ee0e7ffb with Code 1.95.3`

### Steps to Reproduce

1. Install `code-server`
2. Start it and open a terminal
3. Wait 2-3 minutes at most

### Expected

The terminal does not disconnect.

### Actual

The terminal disconnects.

### Logs

```shell
[2024-12-17T13:47:05.911Z] info  code-server 4.95.3 b0c935a6e0742adde9f7a5f6e5816553ee0e7ffb
[2024-12-17T13:47:05.912Z] info  Using user-data-dir /home/coder/.local/share/code-server
[2024-12-17T13:47:05.925Z] info  Using config file /home/coder/.config/code-server/config.yaml
[2024-12-17T13:47:05.925Z] info  HTTP server listening on http://127.0.0.1:8080/
[2024-12-17T13:47:05.925Z] info    - Authentication is enabled
[2024-12-17T13:47:05.925Z] info      - Using password from /home/coder/.config/code-server/config.yaml
[2024-12-17T13:47:05.925Z] info    - Not serving HTTPS
[2024-12-17T13:47:05.925Z] info  Using proxy URI in PORTS tab: https://{{port}}--dev--catfood--phorcys420--apps.dev.coder.com
[2024-12-17T13:47:05.925Z] info  Session server listening on /home/coder/.local/share/code-server/code-server-ipc.sock
[13:47:10]




[13:47:10] Extension host agent started.
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js
[13:47:15] [127.0.0.1][2676939d][ManagementConnection] New connection established.
[13:47:18] [127.0.0.1][9fd98aab][ExtensionHostConnection] New connection established.
[13:47:18] [127.0.0.1][9fd98aab][ExtensionHostConnection] <438850> Launched Extension Host Process.
```

### Screenshot/Video

![Image](https://github.com/user-attachments/assets/c1e79d19-6c9c-46d3-ba39-e1756ede50be)
![Image](https://github.com/user-attachments/assets/3aa6b61b-8d69-47b7-8ccc-071c14842a29)

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

### Notes

Running `npm install vsda` in `/usr/lib/code-server/lib/vscode` is not a valid workaround and generates other issues:
```
[2024-12-17T13:55:09.475Z] info  code-server 4.95.3 b0c935a6e0742adde9f7a5f6e5816553ee0e7ffb
[2024-12-17T13:55:09.476Z] info  Using user-data-dir /home/coder/.local/share/code-server
[2024-12-17T13:55:09.488Z] info  Using config file /home/coder/.config/code-server/config.yaml
[2024-12-17T13:55:09.488Z] info  HTTP server listening on http://127.0.0.1:8080/
[2024-12-17T13:55:09.488Z] info    - Authentication is enabled
[2024-12-17T13:55:09.488Z] info      - Using password from /home/coder/.config/code-server/config.yaml
[2024-12-17T13:55:09.488Z] info    - Not serving HTTPS
[2024-12-17T13:55:09.488Z] info  Using proxy URI in PORTS tab: https://{{port}}--dev--catfood--phorcys420--apps.dev.coder.com
[2024-12-17T13:55:09.488Z] info  Session server listening on /home/coder/.local/share/code-server/code-server-ipc.sock
[13:55:30] Extension host agent started.
[2024-12-17T13:55:32.082Z] error this.s.validator is not a constructor TypeError: this.s.validator is not a constructor
    at Wd.D (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:590)
    at Wd.handleUpgrade (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:91)
    at /usr/lib/code-server/out/node/routes/vscode.js:205:18
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/routes/vscode.js:28:58)
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js
[2024-12-17T13:55:43.502Z] error this.s.validator is not a constructor TypeError: this.s.validator is not a constructor
    at Wd.D (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:590)
    at Wd.handleUpgrade (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:91)
    at /usr/lib/code-server/out/node/routes/vscode.js:205:18
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/routes/vscode.js:28:58)
[2024-12-17T13:55:55.503Z] error this.s.validator is not a constructor TypeError: this.s.validator is not a constructor
    at Wd.D (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:590)
    at Wd.handleUpgrade (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:91)
    at /usr/lib/code-server/out/node/routes/vscode.js:205:18
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/routes/vscode.js:28:58)
[2024-12-17T13:56:07.584Z] error this.s.validator is not a constructor TypeError: this.s.validator is not a constructor
    at Wd.D (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:590)
    at Wd.handleUpgrade (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:91)
    at /usr/lib/code-server/out/node/routes/vscode.js:205:18
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/routes/vscode.js:28:58)
[2024-12-17T13:56:19.551Z] error this.s.validator is not a constructor TypeError: this.s.validator is not a constructor
    at Wd.D (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:590)
    at Wd.handleUpgrade (file:///usr/lib/code-server/lib/vscode/out/server-main.js:206:91)
    at /usr/lib/code-server/out/node/routes/vscode.js:205:18
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/code-server/out/node/routes/vscode.js:28:58)
```

**Comment by vacerde** [comment]
This error also occurs when using Version 4.91.1 1962f48b7f71772dc2c060dbaa5a6b4c0792a549 with Code 1.91.1


`
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at D.U (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:30811)
    at D.updateTitle (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:26011)
    at I.P.<computed> (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:21286)
    at Object.call (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:36:5367)
    at a.s (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
    at a.q (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
    at w.value (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
    at n.B (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:30:742)
    at n.fire (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:30:959)
    at process.we (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:25:27577)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[20:09:38] Error [CodeExpectedError]: Could not find pty on pty host
    at D.U (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:30811)
    at D.updateTitle (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:26011)
    at I.P.<computed> (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:54:21286)
    at Object.call (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:36:5367)
    at a.s (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:5506)
    at a.q (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:4947)
    at w.value (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:34:4247)
    at n.B (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:30:742)
    at n.fire (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:30:959)
    at process.we (/usr/lib/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:25:27577)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[20:09:43] [127.0.0.1][e77c45cb][ExtensionHostConnection] The client has reconnected.
[20:09:56] No ptyHost heartbeat after 6 seconds
[20:10:01] No ptyHost heartbeat after 12 seconds
`

**Comment by IkeNefcy** [comment]
This is happening to me with SSH in VS Code 1.96.2, But only on some hosts. I tried using a friends host which was c6g.4xLarge, and I had no issues. On my c7g.4xLarge I have this issue. In vs code Server output I get 
`[error] ptyHost terminated unexpectedly with code null`, I've tried the usual, deleting .vscode-server, reinstalling vscode locally, Extension Bisect. I even replaced the host with a fresh one and it's still happening. When I ssh via local terminal (mac) I have no issues staying connected. Only in the vs code terminal do I have issues.

**Comment by IkeNefcy** [comment]
Anyone know where more detailed logs would be located I can check for?

**Comment by phorcys420** [comment]
User has reinstalled their OS since and they don't face the issue anymore.
